window.QCM = (window.QCM || []).concat([
/* ============ QCM NIVEAU 10 — ENTRETIEN SENIOR : ARBITRAGES ============ */

{ id:"c10-01", lvl:10, dom:"SRE",
  q:"« Votre solution est trop complexe pour notre équipe. » Meilleure réaction ?",
  choix:["Reformuler l'objection, reconnaître ce qui est vrai, proposer une version dégradée en disant ce qu'on perd","Défendre ta proposition avec des arguments techniques supplémentaires","Accepter immédiatement et proposer autre chose","Expliquer que l'équipe montera en compétence"],
  bonne:0,
  explain:"Un senior teste si tu SAIS ARBITRER, pas si tu as raison. Camper et céder sans argument sont les deux échecs symétriques." },

{ id:"c10-02", lvl:10, dom:"SRE",
  q:"Premier jour sur une plateforme que tu ne connais pas. Que fais-tu ?",
  choix:["Tu écoutes et tu cartographies : flux critiques, incidents récents, ce qui réveille les gens la nuit","Tu mets en place le monitoring qui manque","Tu proposes un plan de migration","Tu audites les configurations de sécurité"],
  bonne:0,
  explain:"Arriver en imposant sa stack est le signal d'alarme numéro un pour un chef d'équipe. On identifie les risques immédiats sans y toucher, puis on pose des quick wins mesurables." },

{ id:"c10-03", lvl:10, dom:"Kubernetes",
  q:"« On veut Kubernetes. » Quelle est la meilleure première réponse ?",
  choix:["« Quel problème cherchez-vous à résoudre, et qui exploitera le cluster à 3 h du matin ? »","« Excellent choix, je commence par l'architecture du cluster »","« Je vous déconseille, c'est trop complexe »","« Combien de nœuds voulez-vous ? »"],
  bonne:0,
  explain:"Kubernetes est un coût opérationnel PERMANENT qu'il faut justifier. Demander quelle alternative plus simple a été écartée, et pourquoi, marque des points." },

{ id:"c10-04", lvl:10, dom:"Terraform",
  q:"« Le state Terraform est un point de défaillance unique. » Que réponds-tu ?",
  choix:["« C'est un risque réel mais géré : backend répliqué, versioning, chiffrement, restauration testée — et reconstructible par import »","« Non, le state est répliqué automatiquement »","« C'est pour ça qu'on préfère les scripts »","« On peut le supprimer et tout recréer »"],
  bonne:0,
  explain:"On ne nie pas l'objection : on montre les contrôles. Et on retourne l'argument : le vrai point de défaillance, c'est l'infrastructure non décrite que personne ne sait recréer." },

{ id:"c10-05", lvl:10, dom:"CI/CD",
  q:"« On met en prod une fois par trimestre et ça marche très bien. » Meilleure approche ?",
  choix:["Pointer le coût caché du gros lot (on ne sait pas quel changement accuse, le rollback annule tout) et proposer un chemin progressif","Expliquer que c'est une pratique dépassée","Accepter, chaque contexte est différent","Proposer de passer directement au déploiement continu"],
  bonne:0,
  explain:"Les données DORA montrent que la fréquence RÉDUIT le taux d'échec. On propose : feature flags, automatisation des tests, viser mensuel avant hebdomadaire." },

{ id:"c10-06", lvl:10, dom:"Sécurité",
  q:"Le RSSI interdit tout accès internet sortant depuis les nœuds Kubernetes. Que fais-tu ?",
  choix:["Registry miroir interne, proxy sortant en liste blanche de FQDN, endpoints privés, CA d'entreprise injectée dans les images","Tu expliques que c'est incompatible avec Kubernetes","Tu demandes une exception pour le registry public","Tu utilises un VPN depuis les nœuds"],
  bonne:0,
  explain:"C'est le standard bancaire. La question teste si tu as déjà travaillé en environnement contraint — répondre « c'est impossible » est éliminatoire." },

{ id:"c10-07", lvl:10, dom:"Sécurité",
  q:"Un développeur demande un accès prod « 10 minutes » pour un incident client. Que fais-tu ?",
  choix:["Élévation juste-à-temps avec approbation, périmètre minimal, expiration automatique et session enregistrée","Tu refuses : la production est interdite aux développeurs","Tu lui donnes ton propre accès","Tu crées un compte permanent avec des droits limités"],
  bonne:0,
  explain:"Puis en post-mortem : pourquoi l'observabilité n'a-t-elle pas suffi à diagnostiquer sans accès ? L'accès prod récurrent est un symptôme d'outillage insuffisant." },

{ id:"c10-08", lvl:10, dom:"SRE",
  q:"Tu racontes un incident. Quelle partie les seniors écoutent-ils le plus ?",
  choix:["Ce que tu as changé DURABLEMENT après","La complexité technique de la panne","La rapidité de ta résolution","Le nombre d'utilisateurs impactés"],
  bonne:0,
  explain:"Un candidat qui ne tire pas d'action systémique d'un incident rejouera le même incident chez eux. Structure : contexte chiffré → détection → décision → résolution → action durable." },

{ id:"c10-09", lvl:10, dom:"SRE",
  q:"« Quelle est la dernière fois où vous vous êtes trompé ? » Pourquoi cette question ?",
  choix:["Elle teste la lucidité : quelqu'un qui n'a jamais tort ne rapportera pas ses erreurs en production","Pour vérifier ton niveau technique","Pour te déstabiliser volontairement","C'est une question RH sans enjeu"],
  bonne:0,
  explain:"Réponse efficace : une vraie erreur avec impact réel, comment tu l'as détectée et assumée, et le garde-fou mis en place après. À éviter : la fausse humilité." },

{ id:"c10-10", lvl:10, dom:"AWS",
  q:"« Concevez une plateforme de paiement à 10 000 transactions/seconde. » Par quoi commences-tu ?",
  choix:["Par clarifier : pic ou soutenu ? latence acceptable ? cohérence forte obligatoire ? contraintes réglementaires ?","Par dessiner l'architecture cible","Par choisir la base de données","Par dimensionner le cluster Kubernetes"],
  bonne:0,
  explain:"Commencer à dessiner sans poser de questions est éliminatoire. Ensuite : idempotence stricte, écriture durable avant acquittement, journal immuable pour l'audit." },

{ id:"c10-11", lvl:10, dom:"SRE",
  q:"Pourquoi l'idempotence est-elle LE concept central d'un système financier distribué ?",
  choix:["On ne sait jamais si un appel a échoué ou si la réponse s'est perdue : sans idempotence, un retry débite deux fois","Elle améliore les performances","Elle simplifie le code","Elle est exigée par le RGPD"],
  bonne:0,
  explain:"Implémentation : une clé d'idempotence fournie par le client, stockée avec le résultat ; un second appel avec la même clé renvoie le résultat initial sans réexécuter." },

{ id:"c10-12", lvl:10, dom:"Kubernetes",
  q:"Trois chefs te contredisent en même temps. Meilleure posture ?",
  choix:["Ramener le débat sur les CRITÈRES : « on optimise pour le time-to-market, le coût d'exploitation ou la conformité ? »","Défendre ta position jusqu'au bout","Te ranger à l'avis du plus gradé","Proposer de reporter la discussion"],
  bonne:0,
  explain:"Puis proposer de trancher par la donnée (POC borné, test de charge) et distinguer décision réversible (on essaie vite) d'irréversible (on prend le temps)." },

{ id:"c10-13", lvl:10, dom:"Terraform",
  q:"Comment expliquer l'intérêt de l'IaC à un directeur, pas à un développeur ?",
  choix:["Réduction du risque opérationnel, reprise après sinistre en heures, preuve d'audit intégrée, moindre dépendance aux personnes","En expliquant HCL et la gestion du state","En montrant un exemple de code","En comparant Terraform à Ansible"],
  bonne:0,
  explain:"Parler de state et de HCL à un directeur est une erreur de registre. Et il faut annoncer le coût réel : formation et discipline." },

{ id:"c10-14", lvl:10, dom:"Observabilité",
  q:"Comment convaincre d'investir dans l'observabilité « alors qu'il n'y a pas d'incident » ?",
  choix:["Chiffrer : temps de diagnostic × coût horaire × nombre d'incidents, plus le coût métier d'une minute d'indisponibilité","Montrer les dashboards des concurrents","Expliquer les trois piliers de l'observabilité","Attendre le prochain incident majeur"],
  bonne:0,
  explain:"L'argument gagnant n'est jamais technique : c'est le temps de diagnostic transformé en euros. Puis proposer un pilote mesurable avec un objectif de MTTR." },

{ id:"c10-15", lvl:10, dom:"Sécurité",
  q:"On te demande de mettre en prod quelque chose que tu juges dangereux. Que fais-tu ?",
  choix:["Expliquer le risque concrètement, proposer une mitigation, et si la décision est maintenue la faire acter par écrit","Refuser catégoriquement","Obéir sans commentaire","Alerter directement la direction générale"],
  bonne:0,
  explain:"Ce qui est évalué : savoir alerter sans bloquer, et accepter qu'on n'est pas le décideur final. L'escalade se réserve aux enjeux majeurs." },

{ id:"c10-16", lvl:10, dom:"CI/CD",
  q:"Comment introduire le GitOps dans une organisation qui déploie via des tickets ?",
  choix:["Déplacer le contrôle sans le supprimer : l'approbation devient une PR, le ticket reste comme trace, on commence par un service pilote","Imposer l'outil et former les équipes ensuite","Supprimer le processus de tickets","Attendre une réorganisation"],
  bonne:0,
  explain:"Imposer l'outil avant d'avoir traité la question du CONTRÔLE échoue systématiquement en banque. On documente la traçabilité pour l'équipe risque, puis on étend." },

{ id:"c10-17", lvl:10, dom:"SRE",
  q:"Qu'est-ce qui distingue un bon runbook d'un mauvais ?",
  choix:["Il part du SYMPTÔME, donne les commandes exactes, dit comment vérifier l'effet et quand escalader — et il a été testé par un tiers","Il décrit précisément l'architecture du système","Il est rédigé par l'expert du domaine","Il est exhaustif et couvre tous les cas"],
  bonne:0,
  explain:"À 3 h du matin, on a besoin d'actions, pas d'un cours d'architecture. Un runbook non testé par quelqu'un d'autre que son auteur suppose toujours un contexte implicite." },

{ id:"c10-18", lvl:10, dom:"Réseau",
  q:"Un flux ne passe pas et quatre équipes se renvoient la balle. Comment tranches-tu ?",
  choix:["En produisant des PREUVES : résolution DNS, test TCP sur le port, capture des deux côtés, flow logs","En organisant une réunion avec les quatre équipes","En escaladant au management","En testant depuis un autre environnement"],
  bonne:0,
  explain:"La capture montre si le SYN arrive et si le SYN-ACK repart : ça localise le point exact de rupture et met fin au débat. Compétence autant méthodologique que politique." },

{ id:"c10-19", lvl:10, dom:"Kubernetes",
  q:"Le cluster va bien, les métriques sont vertes, mais les utilisateurs se plaignent. Que fais-tu ?",
  choix:["Mesurer depuis le POINT DE VUE utilisateur (tests synthétiques externes, RUM) et segmenter par région, endpoint, version de client","Vérifier à nouveau les dashboards du cluster","Demander aux utilisateurs de vider leur cache","Augmenter le nombre de réplicas"],
  bonne:0,
  explain:"Le problème est presque toujours hors du périmètre observé : DNS, CDN, WAF, certificat, réseau opérateur. « Mes dashboards sont verts » n'est jamais une réponse acceptable." },

{ id:"c10-20", lvl:10, dom:"SRE",
  q:"Quelle question poser en fin d'entretien a le plus de valeur ?",
  choix:["« Quel a été le dernier incident majeur, et qu'est-ce qui a changé après ? »","« Quelles technologies utilisez-vous ? »","« Quelle est la politique de télétravail ? »","« Quand aurai-je une réponse ? »"],
  bonne:0,
  explain:"Elle montre que tu penses en exploitant et que tu t'intéresses à leur culture d'amélioration. Ne poser aucune question casse une bonne performance technique." },

{ id:"c10-21", lvl:10, dom:"Sécurité",
  q:"Comment expliquer à un métier qu'il faut arrêter les mots de passe partagés dans un Excel ?",
  choix:["« Aujourd'hui, si quelqu'un fait une erreur ou part, on ne peut ni savoir qui a agi ni couper son accès sans bloquer tout le monde »","En expliquant les risques de chiffrement du fichier","En citant la politique de sécurité interne","En montrant des exemples de fuites dans la presse"],
  bonne:0,
  explain:"On parle traçabilité, révocation individuelle et responsabilité — pas cryptographie. Puis on propose une solution qui ne dégrade pas leur quotidien." },

{ id:"c10-22", lvl:10, dom:"AWS",
  q:"Ton prédécesseur a laissé une infra créée à la main, sans documentation. Plan sur 3 mois ?",
  choix:["Inventaire → geler la création manuelle → vérifier sauvegardes et accès d'urgence → reprise en IaC par import, en commençant par le socle","Tout réécrire en Terraform depuis zéro","Migrer vers un nouveau compte propre","Documenter l'existant pendant trois mois"],
  bonne:0,
  explain:"Arrêter l'hémorragie avant de nettoyer : exiger l'IaC pour tout ce qui est NOUVEAU. Vouloir tout réécrire d'un coup est le piège." },

{ id:"c10-23", lvl:10, dom:"SRE",
  q:"« On n'a pas le temps de faire les choses proprement. » Meilleure réponse ?",
  choix:["Accepter la contrainte mais la NOMMER comme dette, tracée avec propriétaire et échéance, et négocier 10-20 % de capacité récurrente","Refuser de livrer sans qualité","Faire proprement quand même, sans le dire","Accepter sans commentaire"],
  bonne:0,
  explain:"Et faire le minimum non négociable maintenant : sauvegardes, rollback, observabilité de base. Un grand chantier futur n'arrive jamais." },

{ id:"c10-24", lvl:10, dom:"Kubernetes",
  q:"Comment expliquer Kubernetes à un chef de projet non technique ?",
  choix:["« Un chef d'orchestre : on lui décrit ce qu'on veut, il s'assure en permanence que c'est le cas et répare tout seul »","« Un système d'orchestration de conteneurs basé sur des contrôleurs déclaratifs »","« Une alternative moderne aux machines virtuelles »","« La technologie utilisée par Google »"],
  bonne:0,
  explain:"Savoir vulgariser est une compétence évaluée : en banque tu dialogueras avec le risque, la conformité et le métier. Zéro acronyme, une analogie du quotidien." },

{ id:"c10-25", lvl:10, dom:"SRE",
  q:"Comment annoncer une zone que tu ne maîtrises pas ?",
  choix:["Nommer précisément la limite, puis montrer ton processus d'apprentissage avec un exemple concret et daté","Éviter le sujet et parler de ce que tu maîtrises","Dire que tu apprendras vite","Minimiser l'importance de cette technologie"],
  bonne:0,
  explain:"Bluffer sur une technologie que trois seniors connaissent est éliminatoire en une relance. « Je ne sais pas, voilà comment je m'y prendrais » est une réponse FORTE." },

{ id:"c10-26", lvl:10, dom:"CI/CD",
  q:"Pourquoi un environnement de recette n'est-il presque jamais identique à la production ?",
  choix:["Volume et nature des données, charge non reproduite, topologie simplifiée, et dérive dès qu'on y touche à la main","Parce que le budget est insuffisant","Parce que les outils ne le permettent pas","Parce que les équipes n'ont pas le temps"],
  bonne:0,
  explain:"D'où : générer les deux avec le MÊME code IaC paramétré, et compléter par des tests en production maîtrisée (canary, shadow traffic) plutôt que de croire à une recette parfaite." },

{ id:"c10-27", lvl:10, dom:"Sécurité",
  q:"Première mesure de sécurité sur une plateforme cloud qui n'en a aucune ?",
  choix:["Verrouiller les IDENTITÉS : MFA, compte racine sécurisé, suppression des clés statiques et comptes dormants","Chiffrer tous les disques","Mettre en place un WAF","Segmenter le réseau"],
  bonne:0,
  explain:"Juste après : activer la journalisation immuable pour pouvoir enquêter. Sans identité maîtrisée, le chiffrement et la segmentation ne protègent rien." },

{ id:"c10-28", lvl:10, dom:"SRE",
  q:"Tu rejoins une équipe où tout est manuel et personne ne veut changer. Premiers 30 jours ?",
  choix:["Comprendre POURQUOI ça n'a pas changé, gagner en crédibilité sur les tâches pénibles, puis automatiser UNE douleur qu'ils ont nommée","Présenter un plan de transformation complet","Automatiser le processus le plus critique","Demander un mandat clair à la direction"],
  bonne:0,
  explain:"Il y a souvent une tentative passée qui a mal fini. Le changement en banque est d'abord un travail de confiance ; arriver en donneur de leçons garantit l'échec." },

{ id:"c10-29", lvl:10, dom:"SRE",
  q:"« Préférez-vous être expert ou généraliste ? » Quel est le piège ?",
  choix:["Choisir un camp de façon absolue : la bonne réponse est le profil en T, avec des profondeurs nommées honnêtement","Répondre « généraliste », c'est ce qu'on attend d'un DevOps","Répondre « expert », ça rassure sur le niveau","Il n'y a pas de piège, c'est une question de préférence"],
  bonne:0,
  explain:"Une base large pour dialoguer avec toutes les équipes et diagnostiquer de bout en bout, plus une ou deux profondeurs réelles. Prétendre être expert de tout face à trois spécialistes est éliminatoire." },

{ id:"c10-30", lvl:10, dom:"CI/CD",
  q:"Avant de sortir de la salle d'entretien, qu'est-ce qui est indispensable ?",
  choix:["Avoir posé tes questions ET demandé les prochaines étapes et le délai","Avoir résumé tes compétences","Avoir remercié chaque intervenant nommément","Avoir demandé un retour immédiat sur ta prestation"],
  bonne:0,
  explain:"Demander les prochaines étapes montre de l'intérêt et t'évite d'attendre dans le flou. Sortir sans rien demander laisse une impression tiède, même après une bonne performance." },

{ id:"c10-31", lvl:10, dom:"SRE",
  q:"« Vous n'avez jamais travaillé en banque. Pourquoi vous prendre ? »",
  choix:["Reconnaître l'écart, montrer ce qui est transférable, et prouver que tu as compris LEUR contexte (conformité, séparation des tâches, gels, réversibilité)","Expliquer que la technique est la même partout","Citer des projets similaires en complexité","Dire que tu apprendras le métier rapidement"],
  bonne:0,
  explain:"Prouver qu'on a fait l'effort de comprendre leur métier vaut plus que dix ans d'expérience générique. On ne s'excuse pas, on ne nie pas." },

{ id:"c10-32", lvl:10, dom:"Sécurité",
  q:"« Notre sécurité ralentit tout. Vous en pensez quoi ? » — c'est un test. Que réponds-tu ?",
  choix:["Les contraintes sont légitimes ; le problème est leur COÛT d'application — il faut les automatiser et les intégrer au chemin par défaut","Vous avez raison, il faudrait assouplir certaines règles","La sécurité passe avant la vitesse, c'est normal","Je trouverais des moyens de contourner les blocages"],
  bonne:0,
  explain:"Le piège est de se ranger du côté de la vitesse pour se rendre sympathique. Un contrôle manuel et répété ralentit ET est mal appliqué : c'est ça qu'on corrige." },

{ id:"c10-33", lvl:10, dom:"AWS",
  q:"« Combien coûterait votre architecture ? » Tu n'as pas les chiffres. Que fais-tu ?",
  choix:["Raisonner en ordre de grandeur à voix haute : postes dominants, hypothèse de volumétrie assumée, fourchette, et ce qui la ferait basculer","Dire que tu ne peux pas répondre sans les données","Donner un chiffre approximatif au hasard","Proposer d'envoyer une estimation par mail"],
  bonne:0,
  explain:"Ce qui est testé : la conscience que chaque choix technique a un prix, pas la capacité à réciter un tarif." },

{ id:"c10-34", lvl:10, dom:"SRE",
  q:"On te donne 6 mois et 4 personnes. Comment cadres-tu ta priorité n°1 ?",
  choix:["Refuser de répondre dans le vide, puis donner ta GRILLE : risque d'abord, toil ensuite, valeur produit enfin — plus un livrable visible sous 6 semaines","Annoncer une migration vers Kubernetes","Commencer par le monitoring","Recruter deux personnes de plus"],
  bonne:0,
  explain:"« Ça dépend de ce que je trouverais, mais voici comment je trancherais » est une réponse forte : elle montre une méthode plutôt qu'une recette." },

{ id:"c10-35", lvl:10, dom:"SRE",
  q:"« Comment sauriez-vous que votre travail a de la valeur ? »",
  choix:["En nommant des mesures : MTTR, réveils nocturnes, lead time, taux d'échec des changements, temps gagné par les équipes produit","« Quand tout fonctionne bien »","« Quand mon manager est satisfait »","« Quand il n'y a plus d'incidents »"],
  bonne:0,
  explain:"Un candidat qui répond « quand ça marche bien » n'a jamais eu à défendre un budget. À ce niveau, on cherche quelqu'un capable de rendre son impact visible sans qu'on le lui demande." }

]);
