window.QCM = (window.QCM || []).concat([
/* ============ QCM NIVEAU 9 — RÉSILIENCE, COÛTS, GOUVERNANCE ============ */

{ id:"c9-01", lvl:9, dom:"SRE",
  q:"Classe ces stratégies DR de la moins chère à la plus chère.",
  choix:["Backup &amp; restore → pilot light → warm standby → actif/actif","Actif/actif → warm standby → pilot light → backup","Pilot light → backup → actif/actif → warm standby","Warm standby → backup → actif/actif → pilot light"],
  bonne:0,
  explain:"RTO respectifs : heures → dizaines de minutes → minutes → quasi nul. Le choix découle du RTO/RPO négocié avec le métier, pas d'une préférence technique." },

{ id:"c9-02", lvl:9, dom:"SRE",
  q:"Une sauvegarde jamais restaurée, c'est :",
  choix:["Une hypothèse, pas une sauvegarde","Une sauvegarde valide tant que l'outil ne remonte pas d'erreur","Suffisant si elle est chiffrée","Conforme si la rétention est respectée"],
  bonne:0,
  explain:"Règle 3-2-1 (3 copies, 2 supports, 1 hors site) + 1 copie immuable contre les ransomwares, et un exercice de restauration CHRONOMÉTRÉ qui valide aussi les clés de chiffrement." },

{ id:"c9-03", lvl:9, dom:"SRE",
  q:"Ta région primaire tombe. Qu'est-ce qu'on oublie le plus souvent ?",
  choix:["TTL DNS trop long, secrets et clés KMS régionaux non répliqués, quotas jamais demandés dans la région de secours","La configuration du load balancer","Le nombre de réplicas applicatifs","Les règles de firewall"],
  bonne:0,
  explain:"Souvent une quatrième : le pipeline de déploiement lui-même hébergé dans la région tombée. D'où la question piège : « votre rollback dépend-il du système qui est tombé ? »" },

{ id:"c9-04", lvl:9, dom:"SRE",
  q:"Comment tester un plan de reprise sans impacter la production ?",
  choix:["Par paliers : restauration technique isolée → game day sur table → bascule d'un composant non critique → bascule complète planifiée","En simulant tout sur un schéma d'architecture","En coupant la production un dimanche matin","En se fiant aux garanties du fournisseur cloud"],
  bonne:0,
  explain:"Chaque palier produit des écarts documentés. Un plan de reprise jamais exercé est une hypothèse — et l'auditeur demandera la date du dernier exercice." },

{ id:"c9-05", lvl:9, dom:"SRE",
  q:"Pourquoi 99,99 % de disponibilité est-il souvent déraisonnable ?",
  choix:["≈ 4 minutes par mois : moins que le temps de détection humaine, et les dépendances managées sont souvent à 99,9 %","Parce que les SLA cloud l'interdisent","Parce que le monitoring ne mesure pas si finement","Parce que c'est réservé aux GAFAM"],
  bonne:0,
  explain:"On ne peut pas être plus fiable que la somme de ses dépendances. C'est l'argument à sortir quand un métier demande « du 100 % »." },

{ id:"c9-06", lvl:9, dom:"Sécurité",
  q:"Comment appliquer la séparation des tâches dans un pipeline automatisé ?",
  choix:["Branches protégées, revue par un tiers, environnements protégés avec approbation distincte, identités build ≠ deploy, journalisation immuable","En interdisant l'automatisation en production","En donnant les droits à une seule personne","En exigeant un ticket ITSM par déploiement"],
  bonne:0,
  explain:"Le contrôle passe du geste manuel à la GOUVERNANCE DU PIPELINE — c'est exactement l'argument qu'un auditeur bancaire attend d'entendre." },

{ id:"c9-07", lvl:9, dom:"Sécurité",
  q:"Un auditeur demande de prouver ce qui tourne en production et qui l'a autorisé. Que montres-tu ?",
  choix:["Ticket → PR revue et approuvée nominativement → commit signé → build tracé avec SBOM → journal de déploiement → inventaire réel","Les captures d'écran de la console cloud","Le fichier de configuration actuel","La liste des administrateurs"],
  bonne:0,
  explain:"En GitOps, le dépôt Git EST la preuve de l'état désiré, et le contrôleur prouve la réconciliation avec l'état réel." },

{ id:"c9-08", lvl:9, dom:"Sécurité",
  q:"Une équipe est bloquée en urgence par une policy de sécurité. Que fais-tu ?",
  choix:["Une exemption nommée, à périmètre limité, avec date d'expiration, propriétaire et justification approuvée","Tu désactives la policy le temps du déploiement","Tu donnes un accès administrateur temporaire","Tu attends la prochaine revue de sécurité"],
  bonne:0,
  explain:"Une exception sans date de fin devient une règle permanente que personne n'assume — c'est exactement ce que cherchent les auditeurs." },

{ id:"c9-09", lvl:9, dom:"Sécurité",
  q:"Qu'est-ce qu'un compte break-glass ?",
  choix:["Un compte d'urgence à privilèges maximaux, scellé, hors fédération, avec alerte immédiate à toute utilisation","Un compte de service partagé par l'équipe","Un compte administrateur nominatif","Un compte de test en production"],
  bonne:0,
  explain:"Sans lui, une panne de l'IdP devient une panne totale sans possibilité d'intervention. Il doit être testé périodiquement et sa rotation faite après chaque usage." },

{ id:"c9-10", lvl:9, dom:"Sécurité",
  q:"Que impose DORA (règlement européen) à un DevOps en banque ?",
  choix:["Gestion du risque IT, notification rapide des incidents majeurs, tests de résilience, surveillance des prestataires tiers critiques","Le chiffrement de toutes les bases de données","L'hébergement exclusif en France","Le passage obligatoire au multi-cloud"],
  bonne:0,
  explain:"Applicable depuis janvier 2025. Concrètement : registre des dépendances, stratégies de sortie, scénarios de bascule testés et documentés." },

{ id:"c9-11", lvl:9, dom:"Sécurité",
  q:"Point RGPD le plus souvent oublié par les équipes techniques ?",
  choix:["Les logs et les sauvegardes contiennent aussi des données personnelles soumises à rétention et effacement","Le chiffrement en transit","Le consentement aux cookies","La localisation du siège social du fournisseur"],
  bonne:0,
  explain:"Un identifiant utilisateur dans les logs est une donnée personnelle. Le droit à l'effacement doit être traité de bout en bout : base, réplicas, logs, sauvegardes." },

{ id:"c9-12", lvl:9, dom:"Sécurité",
  q:"Comment protéger les sauvegardes contre un ransomware ?",
  choix:["Copies dans un compte/tenant SÉPARÉ, immuables (Object Lock, Vault Lock), inaccessibles en écriture aux identités de production","Un chiffrement fort des sauvegardes","Une rétention de 10 ans","Des sauvegardes plus fréquentes"],
  bonne:0,
  explain:"Le principe : un attaquant qui compromet la production ne doit pas pouvoir atteindre les sauvegardes. Chiffrer ne protège pas de la suppression." },

{ id:"c9-13", lvl:9, dom:"SRE",
  q:"Quelles sont les trois phases du FinOps ?",
  choix:["Inform, Optimize, Operate","Plan, Build, Run","Measure, Reduce, Report","Budget, Forecast, Control"],
  bonne:0,
  explain:"Inform (visibilité, tagging, showback) → Optimize (rightsizing, engagements, architecture) → Operate (budgets, alertes, coût intégré aux critères de conception)." },

{ id:"c9-14", lvl:9, dom:"SRE",
  q:"Une équipe veut du multi-cloud « pour ne pas être verrouillée ». Que réponds-tu ?",
  choix:["Ça coûte cher et réduit souvent la fiabilité ; on préfère une portabilité raisonnable et une stratégie de sortie documentée","Excellente idée, on démarre tout de suite","C'est techniquement impossible","Il faut d'abord migrer tout sur un seul cloud"],
  bonne:0,
  explain:"Le multi-cloud actif/actif impose double compétence, double outillage, dénominateur commun de services. Il se justifie par une exigence réglementaire ou une acquisition, pas par la peur." },

{ id:"c9-15", lvl:9, dom:"SRE",
  q:"Le coût d'un cluster Kubernetes mutualisé explose. Comment identifier qui consomme ?",
  choix:["Allouer le coût des nœuds au prorata des <b>requests</b> par namespace (OpenCost, Kubecost)","Compter le nombre de Pods par équipe","Regarder l'usage CPU réel uniquement","Diviser la facture par le nombre d'équipes"],
  bonne:0,
  explain:"On repère alors les classiques : requests surdimensionnées « au cas où », environnements de test jamais éteints, volumes orphelins." },

{ id:"c9-16", lvl:9, dom:"SRE",
  q:"Comment mettre en place une refacturation crédible des coûts cloud ?",
  choix:["Séparation structurelle (un compte/subscription par équipe) + tagging obligatoire par policy + un propriétaire budgétaire nommé","Un rapport mensuel envoyé à la direction","Une clé de répartition au nombre d'employés","Des quotas par équipe"],
  bonne:0,
  explain:"Sans propriétaire budgétaire, aucun rapport ne change quoi que ce soit. Les coûts partagés doivent avoir une règle d'allocation acceptée à l'avance." },

{ id:"c9-17", lvl:9, dom:"Kubernetes",
  q:"Comment planifier la mise à jour d'un cluster en production bancaire ?",
  choix:["Notes de version et API dépréciées → compatibilité des addons → rejeu en recette → plan de contrôle puis nœuds par lots → une mineure à la fois","Tout mettre à jour d'un coup une nuit","Recréer un cluster neuf et basculer le DNS","Attendre la version LTS suivante"],
  bonne:0,
  explain:"Avec PDB en place, surge upgrade, fenêtre annoncée, plan de repli documenté et validation métier après chaque lot." },

{ id:"c9-18", lvl:9, dom:"Kubernetes",
  q:"Comment garantir que seules des images approuvées tournent sur le cluster ?",
  choix:["Une politique d'admission qui exige un registry approuvé, un digest et une signature vérifiée","Un scan bloquant en CI","Un registry privé","Une revue de code des manifestes"],
  bonne:0,
  explain:"En amont : registry miroir avec bases durcies, scan bloquant, interdiction réseau du pull depuis internet. L'admission rend le contrôle non contournable." },

{ id:"c9-19", lvl:9, dom:"Kubernetes",
  q:"Comment justifier Kubernetes auprès d'un RSSI bancaire ?",
  choix:["En traduisant chaque exigence en contrôle technique auditable : RBAC, admission policies, NetworkPolicy, images signées, audit exporté vers le SIEM","En citant les autres banques qui l'utilisent","En expliquant que c'est un standard CNCF","En promettant un cluster dédié par application"],
  bonne:0,
  explain:"Le message : Kubernetes est un plan de contrôle AUDITABLE, plus contrôlable qu'un parc de VM administrées à la main." },

{ id:"c9-20", lvl:9, dom:"Terraform",
  q:"Comment monter une version MAJEURE de provider sur 40 states ?",
  choix:["Lire le guide de migration, épingler partout, plan à blanc en non-prod, corriger, dérouler par lots du moins risqué au plus risqué","Lancer un apply global avec la nouvelle version","Laisser Terraform gérer automatiquement","Migrer uniquement la production d'abord"],
  bonne:0,
  explain:"Le risque est la destruction/recréation silencieuse. On ne monte JAMAIS un provider majeur sans plan préalable relu par un humain." },

{ id:"c9-21", lvl:9, dom:"Terraform",
  q:"À quels moments applique-t-on le Policy as Code sur l'infrastructure ?",
  choix:["En CI sur le plan, à l'admission côté plateforme, et en continu sur l'existant","Uniquement en CI, c'est le moins cher","Uniquement à l'admission","Uniquement lors des audits annuels"],
  bonne:0,
  explain:"La CI seule ne suffit jamais : quelqu'un finira par agir hors pipeline. L'admission (Azure Policy Deny, SCP, Kyverno) rend le contrôle non contournable." },

{ id:"c9-22", lvl:9, dom:"Terraform",
  q:"Comment appliquer la séparation des tâches sur un pipeline Terraform ?",
  choix:["Identité de plan en LECTURE seule, identité d'apply en écriture déclenchée après merge et approbation","Une seule identité avec tous les droits, mais journalisée","Un mot de passe partagé connu de deux personnes","Un apply manuel depuis le poste d'un référent"],
  bonne:0,
  explain:"Le job de plan tourne sur du code non encore revu, y compris des forks : il ne doit rien pouvoir modifier." },

{ id:"c9-23", lvl:9, dom:"CI/CD",
  q:"Comment concilier déploiement continu et périodes de gel réglementaires ?",
  choix:["Découpler déploiement et activation par feature flags, avec un chemin d'urgence encadré","Suspendre toute la CI pendant le gel","Déployer quand même en le documentant après coup","Fusionner tous les changements après le gel"],
  bonne:0,
  explain:"Le code part en production désactivé ; l'activation métier respecte le calendrier. Les gels (clôtures, arrêtés) sont une contrainte métier LÉGITIME, pas une résistance au changement." },

{ id:"c9-24", lvl:9, dom:"CI/CD",
  q:"Comment garantir la réversibilité d'un déploiement au sens réglementaire ?",
  choix:["Une procédure de rollback automatisée, TESTÉE régulièrement et chronométrée","Une documentation détaillée de la procédure","Une sauvegarde avant chaque déploiement","L'accord préalable du responsable de production"],
  bonne:0,
  explain:"L'auditeur ne demandera pas si vous POUVEZ revenir en arrière : il demandera quand vous l'avez démontré pour la dernière fois." },

{ id:"c9-25", lvl:9, dom:"CI/CD",
  q:"Quelle stratégie de versionnement pour une plateforme partagée par 15 équipes ?",
  choix:["Versionnement sémantique par tags immuables, dépréciation annoncée, N-1 supporté, changelog","Tout le monde consomme la branche main","Une version figée pendant un an","Une branche par équipe consommatrice"],
  bonne:0,
  explain:"Ce qui casse une plateforme partagée, c'est le changement non versionné sur <code>main</code> : on casse 15 équipes en une fois." },

{ id:"c9-26", lvl:9, dom:"Sécurité",
  q:"Une CVE critique sort sur une bibliothèque très utilisée. Que fais-tu dans les 2 premières heures ?",
  choix:["Déterminer si on est concerné et où, grâce au SBOM, et quelles applications sont exposées","Patcher toutes les applications immédiatement","Couper les services exposés","Attendre le correctif officiel de l'éditeur"],
  bonne:0,
  explain:"Sans SBOM à jour, on passe la journée à chercher. Puis : mitigation temporaire si pas de correctif, correction de la base ou de la dépendance partagée, redéploiement par ordre d'exposition." },

{ id:"c9-27", lvl:9, dom:"Sécurité",
  q:"Comment gérer les vulnérabilités sur 300 applications ?",
  choix:["Inventaire par SBOM, priorisation par risque réel, délais contractualisés par criticité, correction à la SOURCE (image de base, lib partagée)","Un ticket par CVE et par application","Un scan hebdomadaire envoyé aux équipes","Bloquer tout déploiement tant qu'il reste une CVE"],
  bonne:0,
  explain:"Corriger à la source évite 300 correctifs unitaires. Le tableau de bord doit être suivi par la direction, avec les exceptions datées." },

{ id:"c9-28", lvl:9, dom:"Observabilité",
  q:"Comment fixer la rétention des logs en banque ?",
  choix:["Par catégorie : obligations légales pour l'audit, mais RGPD impose de NE PAS conserver indéfiniment les données personnelles","Le plus longtemps possible","30 jours pour tout","Selon le budget disponible"],
  bonne:0,
  explain:"Deux exigences contradictoires à concilier, puis une rétention par palier : chaud requêtable, froid, archive immuable pour le légal. Et on documente la politique." },

{ id:"c9-29", lvl:9, dom:"Observabilité",
  q:"Comment construire un SLO à partir de zéro ?",
  choix:["Parcours critique → SLI mesuré CÔTÉ UTILISATEUR → cible issue de l'historique → fenêtre 28-30 j → budget d'erreur → validation métier","Fixer 99,9 % par défaut et ajuster ensuite","Reprendre le SLA du fournisseur cloud","Mesurer l'uptime des serveurs"],
  bonne:0,
  explain:"Mesurer au load balancer, pas dans l'application : ce qui casse avant elle compte aussi. Un SLO que le métier n'assume pas ne sert à rien." },

{ id:"c9-30", lvl:9, dom:"Observabilité",
  q:"Quels SLO définit-on pour une plateforme interne (cluster, pipeline) ?",
  choix:["Disponibilité de l'API du cluster, délai merge → recette, taux de succès des pipelines, délai de provisionnement","Le CPU moyen des nœuds","Le nombre de déploiements par jour","La taille du cluster"],
  bonne:0,
  explain:"Les utilisateurs sont les équipes internes : les SLI doivent porter sur ce qu'elles subissent. C'est ce qui transforme une équipe plateforme en fournisseur mesurable." },

{ id:"c9-31", lvl:9, dom:"SRE",
  q:"Comment migrer un monolithe critique sans big bang ?",
  choix:["Strangler fig : une façade devant le legacy, extraction d'un domaine à la fois, routage progressif, chaque étape réversible","Réécrire complètement puis basculer un week-end","Migrer d'abord le cœur métier","Doubler l'équipe pendant six mois"],
  bonne:0,
  explain:"On commence par un domaine périphérique à faible risque pour valider la mécanique, jamais par le cœur. Avec double run et réconciliation automatique des écarts." },

{ id:"c9-32", lvl:9, dom:"SRE",
  q:"Comment mesurer qu'une transformation DevOps réussit ?",
  choix:["Métriques DORA en tendance + indicateurs humains : toil, réveils nocturnes, satisfaction des équipes","Nombre de pipelines créés","Pourcentage de couverture de tests","Nombre d'outils déployés"],
  bonne:0,
  explain:"Une transformation qui accélère la livraison en épuisant les équipes n'est pas une réussite : elle est en dette." },

{ id:"c9-33", lvl:9, dom:"SRE",
  q:"Comment détecter une surcharge d'équipe AVANT le burn-out ?",
  choix:["Suivre le nombre de réveils par tour d'astreinte et le ratio interruptions/travail planifié, avec des seuils déclenchant une action","Faire un sondage annuel","Compter les heures supplémentaires","Attendre les demandes de mutation"],
  bonne:0,
  explain:"Les seuils doivent être définis à l'avance et déclencher une action concrète : renfort, gel des nouveautés, chantier d'automatisation." },

{ id:"c9-34", lvl:9, dom:"AWS",
  q:"Comment centraliser la sécurité sur 100 comptes AWS ?",
  choix:["CloudTrail organisationnel vers un compte Log Archive immuable, GuardDuty/Security Hub/Config par l'organisation, SCP interdisant la désactivation","Un rôle d'audit dans chaque compte","Un script quotidien de collecte","Une console partagée par les administrateurs"],
  bonne:0,
  explain:"Point clé : le compte de logs doit être inaccessible en écriture aux comptes producteurs. Les traces doivent survivre à la compromission du compte qu'elles observent." },

{ id:"c9-35", lvl:9, dom:"AWS",
  q:"Que demande DORA en matière de stratégie de sortie du cloud ?",
  choix:["Savoir COMMENT on sortirait, en combien de temps et à quel coût — pas d'être multi-cloud","Être obligatoirement présent chez deux fournisseurs","Héberger une copie sur site","Renégocier le contrat chaque année"],
  bonne:0,
  explain:"En pratique : documenter les dépendances propriétaires, privilégier des standards portables sur le chemin critique, garantir l'exportabilité des données avec un délai mesuré." },

{ id:"c9-36", lvl:9, dom:"Azure",
  q:"Comment imposer « données en France uniquement » sur tout un tenant ?",
  choix:["Initiative Azure Policy « Allowed locations » en mode Deny, assignée au management group racine","Un NSG bloquant les IP étrangères","Une convention de nommage des ressources","Une revue mensuelle des déploiements"],
  bonne:0,
  explain:"L'assignation au management group couvre les abonnements présents et futurs. Attention aux réplications géo (GRS vers la région appairée) et aux logs qui peuvent sortir du périmètre." },

{ id:"c9-37", lvl:9, dom:"SQL",
  q:"De quoi dépend un point-in-time recovery ?",
  choix:["D'une sauvegarde complète ET de la conservation continue des journaux de transactions","Des snapshots quotidiens uniquement","De la réplication vers un réplica de lecture","Du mode d'isolation de la base"],
  bonne:0,
  explain:"C'est ce qui permet de revenir juste avant un DELETE catastrophique — à condition de l'avoir testé, car restaurer une grosse base prend des heures." },

{ id:"c9-38", lvl:9, dom:"SQL",
  q:"Quel est l'écueil principal de l'anonymisation des données de test ?",
  choix:["Perdre la cohérence référentielle et le format : les tests ne valent alors plus rien","Le temps de traitement","Le coût du stockage","L'incompatibilité avec les ORM"],
  bonne:0,
  explain:"Même client → même pseudonyme partout, IBAN valide mais fictif. Attention aussi à la ré-identification par croisement. C'est une exigence RGPD, pas une option." }

]);
