window.QCM = (window.QCM || []).concat([
/* ============ QCM NIVEAU 3 — USAGE QUOTIDIEN ============ */

{ id:"c3-01", lvl:3, dom:"Linux",
  q:"La load average est à 8 sur une machine à 4 cœurs, mais le CPU est à 10 %. Que conclus-tu ?",
  choix:["Saturation d'I/O : la load compte aussi les processus en attente ininterruptible","Le CPU est mal mesuré","Il faut ajouter des cœurs","La machine est en train de redémarrer"],
  bonne:0,
  explain:"Sous Linux, la load inclut les processus en état D (attente disque, NFS). À croiser avec <code>%iowait</code> via <code>top</code>, <code>vmstat</code> ou <code>iostat</code>." },

{ id:"c3-02", lvl:3, dom:"Linux",
  q:"Quelle commande rend un service systemd actif MAINTENANT et au prochain démarrage ?",
  choix:["<code>systemctl enable --now mon.service</code>","<code>systemctl start mon.service</code>","<code>systemctl enable mon.service</code>","<code>systemctl restart mon.service</code>"],
  bonne:0,
  explain:"<code>enable</code> seul crée le lien pour le boot sans rien lancer — piège très fréquent. <code>--now</code> ajoute le démarrage immédiat." },

{ id:"c3-03", lvl:3, dom:"Linux",
  q:"Différence entre un hard link et un symlink ?",
  choix:["Le hard link pointe le même inode ; le symlink stocke un chemin et devient mort si la cible disparaît","Le hard link peut traverser les systèmes de fichiers, pas le symlink","Le symlink duplique les données","Aucune, ce sont deux noms du même mécanisme"],
  bonne:0,
  explain:"Supprimer l'original ne casse pas un hard link : le contenu vit tant qu'il reste un lien. Le symlink, lui, peut traverser les systèmes de fichiers et pointer un répertoire." },

{ id:"c3-04", lvl:3, dom:"Linux",
  q:"Pourquoi <code>sort</code> est-il indispensable avant <code>uniq</code> ?",
  choix:["<code>uniq</code> ne dédoublonne que des lignes ADJACENTES","<code>uniq</code> exige une entrée triée pour des raisons de performance","<code>sort</code> supprime déjà les doublons","Ce n'est pas nécessaire"],
  bonne:0,
  explain:"D'où l'idiome <code>sort | uniq -c | sort -rn</code> pour obtenir un classement des occurrences." },

{ id:"c3-05", lvl:3, dom:"Linux",
  q:"Ton service échoue avec « Too many open files ». Quel est le bon réflexe ?",
  choix:["Regarder <code>/proc/&lt;pid&gt;/limits</code>, corriger <code>LimitNOFILE</code> dans l'unité systemd — et chercher la fuite","Ajouter <code>ulimit -n 65536</code> dans le .bashrc","Redémarrer la machine","Augmenter la RAM"],
  bonne:0,
  explain:"Le <code>ulimit</code> du shell ne s'applique pas à un service systemd. Et la vraie question reste la fuite : sockets non fermés, connexions en CLOSE_WAIT, absence de pool." },

{ id:"c3-06", lvl:3, dom:"Linux",
  q:"Pourquoi <code>tail -f</code> cesse-t-il d'afficher après une rotation de logs ?",
  choix:["Il suit le descripteur de fichier, donc l'ancien fichier renommé — <code>tail -F</code> suit le nom","La rotation coupe le processus tail","Le fichier est compressé","Les permissions changent"],
  bonne:0,
  explain:"Détail qui trahit l'expérience terrain. Même logique côté logrotate : il faut signaler au process de rouvrir son fichier (postrotate) ou utiliser <code>copytruncate</code>." },

{ id:"c3-07", lvl:3, dom:"Git",
  q:"Comment retrouver le commit qui a introduit un bug parmi 500 commits ?",
  choix:["<code>git bisect</code> : dichotomie, ~9 tests suffisent","<code>git log --all</code> et lecture manuelle","<code>git blame</code> sur chaque fichier","<code>git diff</code> entre le premier et le dernier commit"],
  bonne:0,
  explain:"<code>git bisect start</code>, <code>bad</code>, <code>good &lt;sha&gt;</code>, puis Git propose les commits intermédiaires. Avec <code>git bisect run ./test.sh</code>, c'est entièrement automatique." },

{ id:"c3-08", lvl:3, dom:"Git",
  q:"Tu as fait <code>git reset --hard</code> et perdu deux commits. Récupérables ?",
  choix:["Oui, via <code>git reflog</code> qui garde l'historique local de HEAD","Non, c'est définitif","Oui, en re-clonant le dépôt","Oui, avec <code>git fsck --repair</code>"],
  bonne:0,
  explain:"Le reflog conserve les positions de HEAD (~90 jours). Ça ne fonctionne que localement, et seulement pour du travail déjà commité." },

{ id:"c3-09", lvl:3, dom:"Git",
  q:"Pourquoi préférer <code>--force-with-lease</code> à <code>--force</code> ?",
  choix:["Il refuse d'écraser si quelqu'un a poussé entre-temps","Il est plus rapide","Il crée une sauvegarde automatique","Il fonctionne sans droits d'écriture"],
  bonne:0,
  explain:"<code>--force</code> écrase le distant quoi qu'il arrive, y compris le travail d'un collègue poussé entre ton fetch et ton push." },

{ id:"c3-10", lvl:3, dom:"Docker",
  q:"Ton conteneur met 10 secondes à s'arrêter avec <code>docker stop</code>. Pourquoi ?",
  choix:["Le PID 1 ne gère pas SIGTERM — souvent parce que le CMD est en forme shell","Le disque est lent","Le réseau doit se fermer proprement","C'est le comportement normal de Docker"],
  bonne:0,
  explain:"En forme shell, c'est <code>/bin/sh -c</code> qui est PID 1 et ne relaie pas les signaux. Après le timeout, Docker envoie SIGKILL. Solutions : forme exec, <code>tini</code>, ou un handler applicatif." },

{ id:"c3-11", lvl:3, dom:"Docker",
  q:"Comment deux conteneurs sur le même hôte se résolvent-ils par nom ?",
  choix:["En les plaçant sur un réseau bridge personnalisé, qui fournit un DNS interne","Via /etc/hosts modifié automatiquement","Par broadcast sur le réseau de l'hôte","C'est impossible sans Kubernetes"],
  bonne:0,
  explain:"Le bridge PAR DÉFAUT n'offre pas la résolution par nom — d'où la recommandation systématique de créer un réseau dédié avec <code>docker network create</code>." },

{ id:"c3-12", lvl:3, dom:"Docker",
  q:"Comment faire tourner un conteneur en non-root ?",
  choix:["Créer un utilisateur dans le Dockerfile puis <code>USER 10001</code>","Ajouter <code>--no-root</code> au docker run","Supprimer le shell de l'image","C'est automatique depuis Docker 20"],
  bonne:0,
  explain:"Côté Kubernetes on complète par <code>runAsNonRoot: true</code>, <code>readOnlyRootFilesystem: true</code> et <code>capabilities.drop: [ALL]</code>. Root dans le conteneur reste souvent root sur l'hôte." },

{ id:"c3-13", lvl:3, dom:"Kubernetes",
  q:"Un Pod reste en <code>Pending</code>. Quelle est la première commande à lancer ?",
  choix:["<code>kubectl describe pod</code> pour lire les Events","<code>kubectl logs</code>","<code>kubectl delete pod</code>","<code>kubectl top pod</code>"],
  bonne:0,
  explain:"Les Events en bas du describe donnent 80 % des réponses : ressources insuffisantes, taints non tolérés, PVC non lié, quota de namespace atteint. <code>logs</code> ne sert à rien : le conteneur n'a pas démarré." },

{ id:"c3-14", lvl:3, dom:"Kubernetes",
  q:"Différence entre CrashLoopBackOff et ImagePullBackOff ?",
  choix:["Crash = le conteneur démarre puis se termine en boucle ; ImagePull = l'image n'a pas pu être téléchargée","Crash concerne le nœud, ImagePull le Pod","ImagePull est temporaire, Crash est définitif","Aucune, ce sont deux affichages du même état"],
  bonne:0,
  explain:"CrashLoop : lire <code>kubectl logs --previous</code> (bug, config manquante, liveness trop stricte, OOM). ImagePull : tag inexistant, imagePullSecret manquant, registry injoignable derrière le proxy." },

{ id:"c3-15", lvl:3, dom:"Kubernetes",
  q:"Que se passe-t-il si un conteneur dépasse sa <code>limit</code> mémoire ?",
  choix:["Il est tué immédiatement (OOMKill), car la mémoire n'est pas compressible","Il est ralenti (throttling)","Il est déplacé sur un autre nœud","Kubernetes augmente la limite automatiquement"],
  bonne:0,
  explain:"Dépassement CPU = throttling (compressible). Dépassement mémoire = OOMKill, exit code 137. C'est LA distinction à connaître." },

{ id:"c3-16", lvl:3, dom:"Kubernetes",
  q:"Quel type de Service provisionne un load balancer cloud ?",
  choix:["LoadBalancer","ClusterIP","NodePort","ExternalName"],
  bonne:0,
  explain:"ClusterIP = interne (défaut). NodePort = un port sur chaque nœud. LoadBalancer = LB cloud pointant vers le NodePort. En production, on met plutôt un Ingress devant UN seul LoadBalancer." },

{ id:"c3-17", lvl:3, dom:"Kubernetes",
  q:"Pour quel besoin utilise-t-on un StatefulSet plutôt qu'un Deployment ?",
  choix:["Identité stable, PVC dédié par Pod, démarrage ordonné — bases, brokers, clusters à quorum","Pour les applications qui consomment beaucoup de CPU","Pour déployer un Pod par nœud","Pour les traitements batch"],
  bonne:0,
  explain:"Noms ordinaux (<code>db-0</code>, <code>db-1</code>), DNS stable via un headless Service. Un Deployment traite ses Pods comme du bétail interchangeable." },

{ id:"c3-18", lvl:3, dom:"Kubernetes",
  q:"À quoi sert un initContainer ?",
  choix:["Exécuter une tâche jusqu'à son terme AVANT les conteneurs principaux","Surveiller le conteneur principal en continu","Initialiser le nœud au démarrage","Remplacer le conteneur en cas de crash"],
  bonne:0,
  explain:"Usages : attendre une dépendance, appliquer une migration, récupérer un fichier de config, ajuster des permissions sur un volume. S'il échoue, le Pod redémarre." },

{ id:"c3-19", lvl:3, dom:"Terraform",
  q:"Pourquoi préférer <code>for_each</code> à <code>count</code> pour des ressources distinctes ?",
  choix:["<code>for_each</code> indexe par CLÉ : supprimer un élément n'affecte pas les autres","<code>count</code> est déprécié","<code>for_each</code> est plus rapide","<code>count</code> ne fonctionne pas avec les modules"],
  bonne:0,
  explain:"<code>count</code> indexe par position : supprimer l'élément 1 sur 3 décale tout et Terraform veut détruire/recréer les suivants. Règle : <code>count</code> uniquement pour un booléen 0/1." },

{ id:"c3-20", lvl:3, dom:"Terraform",
  q:"Comment intégrer dans Terraform une ressource créée à la main ?",
  choix:["Écrire la ressource, puis <code>terraform import</code> (ou un bloc <code>import</code>), puis itérer sur le plan","<code>terraform refresh</code> la détecte automatiquement","<code>terraform apply -sync</code>","Ce n'est pas possible, il faut la recréer"],
  bonne:0,
  explain:"L'import ne génère PAS le code. Le bloc <code>import</code> (1.5+) est préférable : déclaratif, versionné, visible dans le plan." },

{ id:"c3-21", lvl:3, dom:"Terraform",
  q:"Pourquoi utilise-t-on rarement <code>depends_on</code> ?",
  choix:["Terraform déduit le graphe des RÉFÉRENCES entre ressources — c'est implicite et suffisant à 95 %","Il est déprécié depuis la version 1.0","Il ralentit le téléchargement des providers","Il ne fonctionne pas dans les modules"],
  bonne:0,
  explain:"On le réserve aux dépendances non exprimables par une référence. En abuser sérialise inutilement le graphe et allonge l'apply." },

{ id:"c3-22", lvl:3, dom:"Terraform",
  q:"Que fait <code>terraform validate</code> que <code>plan</code> ne fait pas ?",
  choix:["Il vérifie syntaxe et cohérence interne SANS appeler les API ni lire le state","Il applique les changements en mode simulation","Il vérifie les permissions IAM","Il teste les modules distants"],
  bonne:0,
  explain:"Très rapide, utilisable sans credentials — donc parfait en première étape de CI. <code>plan</code> interroge réellement le fournisseur." },

{ id:"c3-23", lvl:3, dom:"AWS",
  q:"Quel type de policy IAM permet un accès cross-compte sans AssumeRole ?",
  choix:["Une resource-based policy (bucket policy, key policy), qui contient un <code>Principal</code>","Une identity-based policy","Une SCP","Une permission boundary"],
  bonne:0,
  explain:"Identity-based : ce que CETTE identité peut faire. Resource-based : qui peut agir sur CETTE ressource. La seconde porte un champ Principal." },

{ id:"c3-24", lvl:3, dom:"AWS",
  q:"Quand choisit-on un NLB plutôt qu'un ALB ?",
  choix:["Protocole non-HTTP, besoin d'IP statique à whitelister, ou performance extrême","Quand on veut router par path ou par host","Quand on a besoin d'un WAF","Quand on utilise des conteneurs"],
  bonne:0,
  explain:"NLB = L4 : latence très faible, millions de connexions, IP statique par AZ, préserve l'IP source, TCP/UDP. ALB = L7 : routage fin, WAF, authentification." },

{ id:"c3-25", lvl:3, dom:"AWS",
  q:"Pourquoi utiliser SSM Session Manager plutôt que SSH sur une instance EC2 ?",
  choix:["Aucun port 22 ouvert, aucune clé à gérer, accès contrôlé par IAM et session journalisée","C'est plus rapide que SSH","Ça fonctionne sans agent installé","Ça permet le transfert de fichiers"],
  bonne:0,
  explain:"C'est la réponse attendue sur « comment accédez-vous aux serveurs en production ». Le bastion classique est lui-même une machine à patcher et une cible." },

{ id:"c3-26", lvl:3, dom:"Azure",
  q:"Quelle différence entre un NSG et l'Azure Firewall ?",
  choix:["Le NSG filtre en L3/L4 sur un subnet ou une NIC ; l'Azure Firewall est un service managé centralisé avec des règles par FQDN","Le NSG est payant, le firewall est gratuit","Le NSG s'applique aux VM, le firewall aux conteneurs","Ils sont interchangeables"],
  bonne:0,
  explain:"L'Azure Firewall vit dans le hub d'une topologie hub-and-spoke : threat intelligence, DNAT/SNAT, journalisation complète, règles applicatives." },

{ id:"c3-27", lvl:3, dom:"Azure",
  q:"Tu crées un Private Endpoint vers un Storage Account, mais l'application joint toujours l'IP publique. Que manque-t-il ?",
  choix:["La Private DNS Zone <code>privatelink.*</code> liée au VNet","Un Security Group sur le subnet","Une route vers l'Internet Gateway","Un redémarrage du Storage Account"],
  bonne:0,
  explain:"Le FQDN public doit résoudre vers l'IP privée : sans Private DNS Zone liée au VNet, on retombe sur l'IP publique. C'est LE piège du Private Endpoint." },

{ id:"c3-28", lvl:3, dom:"Azure",
  q:"Un utilisateur a le rôle Owner sur une subscription. Une Azure Policy en mode Deny le bloque-t-elle ?",
  choix:["Oui : le RBAC dit QUI peut agir, la Policy dit CE QUI peut exister","Non, Owner contourne toutes les policies","Seulement si la policy est assignée au niveau management group","Non, sauf si la policy est en mode Enforce"],
  bonne:0,
  explain:"Ce sont deux plans distincts et complémentaires. Une policy Deny bloque la création non conforme, quel que soit le rôle." },

{ id:"c3-29", lvl:3, dom:"CI/CD",
  q:"Pourquoi un runner de CI doit-il être éphémère ?",
  choix:["Pour éviter cache pollué, dépendances résiduelles et secrets laissés par un job précédent","Pour réduire la facture cloud","Parce que les runners persistants sont dépréciés","Pour permettre le parallélisme"],
  bonne:0,
  explain:"Un runner persistant devient un point de compromission latérale entre projets. D'où les runners conteneurisés jetables." },

{ id:"c3-30", lvl:3, dom:"CI/CD",
  q:"Qu'est-ce qui distingue le GitOps d'un pipeline push classique ?",
  choix:["Un agent DANS le cluster tire depuis Git et réconcilie en continu — pas de credentials cluster dans la CI","Le GitOps n'utilise pas de pipeline","Le GitOps déploie plus vite","Le GitOps ne fonctionne qu'avec Helm"],
  bonne:0,
  explain:"Conséquences : dérive détectée et corrigée, rollback = <code>git revert</code>, audit natif par l'historique Git, et un nouveau cluster se reconstruit en pointant l'agent sur le dépôt." },

{ id:"c3-31", lvl:3, dom:"Sécurité",
  q:"Quel mécanisme évite tout secret longue durée entre un pipeline CI et le cloud ?",
  choix:["La fédération d'identité OIDC : le pipeline échange un token signé contre des credentials temporaires","Un secret stocké chiffré dans les variables du pipeline","Une clé d'accès avec rotation trimestrielle","Un certificat client renouvelé chaque année"],
  bonne:0,
  explain:"Le meilleur secret est celui qui n'existe pas. À défaut : coffre avec injection au runtime, scope par environnement, masquage des logs et rotation." },

{ id:"c3-32", lvl:3, dom:"Sécurité",
  q:"À quel moment du pipeline place-t-on un scan DAST ?",
  choix:["En recette, contre l'application déployée et en cours d'exécution","Au commit, sur le code source","Au build, sur les dépendances","En pre-commit, sur le poste du développeur"],
  bonne:0,
  explain:"SAST = analyse statique du code (tôt). SCA = dépendances et CVE (au build + veille continue). DAST = test dynamique contre l'application qui tourne." },

{ id:"c3-33", lvl:3, dom:"Observabilité",
  q:"Pourquoi alerte-t-on sur les symptômes plutôt que sur les causes ?",
  choix:["Alerter sur un CPU à 90 % génère du bruit alors que le service va peut-être très bien","Les causes sont plus difficiles à mesurer","Les symptômes se détectent plus vite techniquement","Pour respecter la norme ISO"],
  bonne:0,
  explain:"On alerte sur ce que l'utilisateur subit : latence, taux d'erreur, saturation (RED/USE). Les causes servent au diagnostic dans le dashboard, pas au réveil nocturne." },

{ id:"c3-34", lvl:3, dom:"SRE",
  q:"Qu'est-ce que le toil au sens SRE ?",
  choix:["Du travail manuel, répétitif, automatisable, sans valeur durable, qui croît avec le service","Toute tâche d'exploitation","Le travail effectué pendant l'astreinte","La dette technique accumulée"],
  bonne:0,
  explain:"Google fixe la limite à 50 % du temps d'un SRE. Au-delà, on arrête les nouveautés pour automatiser. C'est l'argument qui justifie un investissement d'outillage." },

{ id:"c3-35", lvl:3, dom:"SQL",
  q:"Quelle est la différence entre <code>WHERE</code> et <code>HAVING</code> ?",
  choix:["<code>WHERE</code> filtre les lignes avant l'agrégation, <code>HAVING</code> filtre les groupes après le GROUP BY","<code>HAVING</code> est plus rapide","<code>WHERE</code> ne fonctionne pas avec les jointures","Ce sont des synonymes selon le SGBD"],
  bonne:0,
  explain:"<code>HAVING</code> peut donc porter sur un agrégat (<code>HAVING COUNT(*) &gt; 5</code>). Pour la performance, filtrer un maximum dans le WHERE." },

{ id:"c3-36", lvl:3, dom:"SQL",
  q:"Quel est le coût d'un index ?",
  choix:["De l'espace disque et un surcoût sur chaque INSERT/UPDATE/DELETE","Uniquement de l'espace disque","Un ralentissement des lectures complexes","Aucun, c'est toujours bénéfique"],
  bonne:0,
  explain:"L'index doit être maintenu à chaque écriture. D'où : indexer les colonnes de filtre et de jointure réellement utilisées, pas tout par précaution." }

]);
