window.QCM = (window.QCM || []).concat([
/* ============ QCM NIVEAU 8 — INTERNES & CAS LIMITES ============ */

{ id:"c8-01", lvl:8, dom:"Kubernetes",
  q:"Si etcd perd le quorum, que se passe-t-il ?",
  choix:["Plus aucune écriture : ni déploiement ni reprogrammation — mais le trafic existant continue de fonctionner","Tous les Pods s'arrêtent immédiatement","Le cluster bascule automatiquement sur un etcd de secours","Les Services cessent de router"],
  bonne:0,
  explain:"C'est une panne du plan de CONTRÔLE, pas du plan de DONNÉES. La distinction est exactement ce qu'un senior attend d'entendre." },

{ id:"c8-02", lvl:8, dom:"Kubernetes",
  q:"Quelle est la limite du mode iptables de kube-proxy à grande échelle ?",
  choix:["Les règles sont évaluées de façon quasi linéaire : au-delà de quelques milliers de Services, ça se dégrade","Il ne supporte pas UDP","Il ne fonctionne pas en multi-nœud","Il empêche les NetworkPolicy"],
  bonne:0,
  explain:"Le mode IPVS utilise des tables de hachage (O(1)) et de vrais algorithmes de répartition. Cilium peut remplacer kube-proxy entièrement par de l'eBPF." },

{ id:"c8-03", lvl:8, dom:"Kubernetes",
  q:"Dans quel ordre s'exécutent les admission webhooks ?",
  choix:["Mutating d'abord, puis validation de schéma, puis validating","Validating d'abord, puis mutating","En parallèle","Dans l'ordre alphabétique de leur nom"],
  bonne:0,
  explain:"Logique : on ne valide qu'après toutes les mutations. Piège d'exploitation : un webhook en <code>failurePolicy: Fail</code> et indisponible bloque tout le cluster." },

{ id:"c8-04", lvl:8, dom:"Kubernetes",
  q:"Pourquoi les contrôleurs Kubernetes doivent-ils être idempotents ?",
  choix:["Ils sont level-triggered : ils réagissent au NIVEAU courant, pas à un événement — la réconciliation est rejouée en boucle","Pour pouvoir tourner en plusieurs réplicas simultanés","Parce que l'API server les relance aléatoirement","Pour économiser des appels réseau"],
  bonne:0,
  explain:"C'est ce qui rend le système auto-réparant même après une perte d'événements : le contrôleur compare état désiré et état observé, quel que soit l'historique." },

{ id:"c8-05", lvl:8, dom:"Kubernetes",
  q:"Un Pod avec un PVC ReadWriteOnce ne redémarre pas sur un autre nœud. Pourquoi ?",
  choix:["Le volume bloc ne peut être attaché qu'à un nœud à la fois : il faut le détachement de l'ancien","Le PVC a expiré","La StorageClass est mal configurée","Le nouveau nœud n'a pas le driver CSI"],
  bonne:0,
  explain:"C'est une PROTECTION contre la double écriture, pas un bug. Forcer prématurément risque de corrompre le système de fichiers." },

{ id:"c8-06", lvl:8, dom:"Kubernetes",
  q:"À quoi sert le mécanisme de leader election entre réplicas d'un contrôleur ?",
  choix:["Un seul réplica agit à la fois : il détient un Lease qu'il renouvelle périodiquement","À répartir la charge entre les réplicas","À élire le nœud maître du cluster","À trier les Pods par priorité"],
  bonne:0,
  explain:"Si le leader cesse de renouveler, le bail expire et un autre prend la main. C'est ce qui permet la haute disponibilité d'un contrôleur sans double exécution." },

{ id:"c8-07", lvl:8, dom:"Kubernetes",
  q:"Que résout le server-side apply ?",
  choix:["L'API suit QUI possède chaque champ : les conflits entre acteurs multiples sont détectés au lieu d'être écrasés","Il accélère les gros déploiements","Il valide le YAML côté client","Il chiffre les objets dans etcd"],
  bonne:0,
  explain:"Il remplace l'ancien mécanisme basé sur l'annotation <code>last-applied-configuration</code>, qui gérait mal la suppression de champs et les acteurs concurrents (dev, opérateur, HPA)." },

{ id:"c8-08", lvl:8, dom:"Kubernetes",
  q:"Pourquoi une JVM peut-elle se faire OOMKill alors que son heap est bien sous la limite ?",
  choix:["Le cgroup compte TOUT : metaspace, piles de threads, buffers directs, code natif — pas seulement le heap","Le heap est mal mesuré par Kubernetes","La JVM ignore les limites mémoire","Le garbage collector consomme la limite"],
  bonne:0,
  explain:"Correctifs : JVM récente avec <code>-XX:MaxRAMPercentage</code>, limite avec 25-30 % de marge au-dessus du heap, et surveillance du working set plutôt que du heap." },

{ id:"c8-09", lvl:8, dom:"Linux",
  q:"Pourquoi forker un processus de 8 Go est-il quasi instantané ?",
  choix:["Le copy-on-write : rien n'est copié tant qu'on n'écrit pas","Le noyau compresse la mémoire","Seul le code est dupliqué, pas les données","Le fork est asynchrone"],
  bonne:0,
  explain:"<code>fork()</code> duplique le processus (mémoire marquée COW), <code>exec()</code> remplace l'image par un autre programme. C'est ce que fait un shell à chaque commande." },

{ id:"c8-10", lvl:8, dom:"Linux",
  q:"Comment un processus zombie disparaît-il ?",
  choix:["Quand son parent lit son code de retour avec <code>wait()</code>, ou quand PID 1 l'adopte et le récolte","Quand le noyau le tue après un délai","Avec <code>kill -9</code>","Au redémarrage uniquement"],
  bonne:0,
  explain:"Dans un conteneur, si PID 1 ne récolte pas, les zombies s'accumulent — d'où l'usage de <code>tini</code> ou <code>docker run --init</code>." },

{ id:"c8-11", lvl:8, dom:"Linux",
  q:"Qu'est-ce que l'overcommit mémoire sous Linux ?",
  choix:["Le noyau accorde plus de mémoire virtuelle que de RAM+swap, en pariant que tout ne sera pas utilisé","Une option à activer pour les serveurs de bases de données","Le fait de dépasser la limite d'un cgroup","Une technique de compression de la RAM"],
  bonne:0,
  explain:"Quand la RAM réelle manque, l'OOM killer choisit une victime selon un score ajustable par <code>oom_score_adj</code>. Dans un conteneur, la limite du cgroup déclenche un OOM local." },

{ id:"c8-12", lvl:8, dom:"Linux",
  q:"Quelle métrique mémoire Kubernetes utilise-t-il pour l'OOM et le HPA ?",
  choix:["Le working set : usage courant moins le page cache récupérable","La mémoire virtuelle (VSZ)","Le RSS brut","La somme des allocations du processus"],
  bonne:0,
  explain:"VSZ est un espace d'adressage réservé, souvent énorme et peu significatif. RSS inclut des pages partagées. Confondre les trois fait échouer le dimensionnement des limites." },

{ id:"c8-13", lvl:8, dom:"Linux",
  q:"Pourquoi seccomp est-il un contrôle de sécurité efficace pour un conteneur ?",
  choix:["Il filtre les appels système autorisés : sans <code>mount</code> ou <code>ptrace</code>, des familles entières d'exploits d'évasion tombent","Il chiffre la mémoire du processus","Il isole le réseau du conteneur","Il empêche l'écriture sur le disque"],
  bonne:0,
  explain:"Le profil <code>RuntimeDefault</code> bloque déjà une bonne partie des appels dangereux — et il n'est pas actif par défaut partout." },

{ id:"c8-14", lvl:8, dom:"Linux",
  q:"Qu'apporte eBPF ?",
  choix:["Exécuter des programmes vérifiés DANS le noyau, sans module ni redémarrage : observabilité, réseau, sécurité runtime","Un nouveau système de fichiers","Un remplaçant de systemd","Un format d'image de conteneur"],
  bonne:0,
  explain:"Applications : observabilité sans instrumenter les applications, Cilium qui remplace kube-proxy et iptables, détection runtime (Falco, Tetragon). Sujet qui marque des points en entretien senior." },

{ id:"c8-15", lvl:8, dom:"Terraform",
  q:"Que se passe-t-il si le processus Terraform est tué pendant un apply ?",
  choix:["Le verrou reste posé et une ressource créée peut ne pas figurer dans le state : elle devient orpheline","Le state est automatiquement restauré","Toutes les ressources créées sont supprimées","Terraform reprend automatiquement au redémarrage"],
  bonne:0,
  explain:"Reprise : <code>force-unlock</code> après vérification, plan, identification des orphelines, puis import ou suppression manuelle. Le conflit de nom trahit l'orpheline." },

{ id:"c8-16", lvl:8, dom:"Terraform",
  q:"Qu'est-ce qu'un « diff perpétuel » ?",
  choix:["L'API renvoie une valeur normalisée différente de celle écrite : Terraform veut modifier à chaque plan","Un conflit entre deux states","Une ressource supprimée manuellement","Un provider trop ancien"],
  bonne:0,
  explain:"Causes : casse, ordre d'une liste, JSON reformaté, valeur par défaut ajoutée côté cloud. Solution préférable : écrire la forme canonique renvoyée par l'API ; sinon <code>ignore_changes</code> ciblé." },

{ id:"c8-17", lvl:8, dom:"Terraform",
  q:"Que signifie <code>sensitive = true</code> sur une variable ?",
  choix:["La valeur est masquée dans l'affichage du plan — elle reste EN CLAIR dans le state","La valeur est chiffrée dans le state","La variable est stockée dans un coffre","La variable devient obligatoire"],
  bonne:0,
  explain:"C'est un garde-fou d'affichage, pas une protection. La vraie protection : chiffrement et contrôle d'accès du state, et surtout ne pas faire transiter le secret par Terraform." },

{ id:"c8-18", lvl:8, dom:"Terraform",
  q:"Pourquoi HashiCorp déconseille-t-il <code>-target</code> en usage courant ?",
  choix:["Il limite le graphe et peut laisser un state partiellement cohérent, masquant une dérive","Il est deux fois plus lent","Il ne fonctionne pas avec les modules","Il désactive le verrouillage"],
  bonne:0,
  explain:"C'est un outil de DÉPANNAGE. En avoir besoin régulièrement signale un state mal découpé." },

{ id:"c8-19", lvl:8, dom:"AWS",
  q:"Quel est le modèle de cohérence de S3 aujourd'hui ?",
  choix:["Cohérence forte en lecture après écriture, y compris pour les overwrites et les DELETE","Cohérence à terme pour les overwrites","Cohérence forte uniquement dans us-east-1","Cohérence configurable par bucket"],
  bonne:0,
  explain:"Depuis décembre 2020, sans surcoût. Avant, seuls les PUT de nouveaux objets l'étaient. Attention : la réplication et les métriques restent asynchrones." },

{ id:"c8-20", lvl:8, dom:"AWS",
  q:"Comment KMS chiffre-t-il un gros volume de données ?",
  choix:["Par enveloppe : il génère une data key, renvoyée en clair ET chiffrée ; la donnée est chiffrée localement","Il chiffre directement les données avec la clé maître","Il délègue au service appelant sans clé","Il utilise un chiffrement asymétrique complet"],
  bonne:0,
  explain:"Avantages : performance, et la clé maître ne quitte jamais le HSM. Au déchiffrement, on redemande à KMS de déchiffrer la data key." },

{ id:"c8-21", lvl:8, dom:"AWS",
  q:"Comment un SDK doit-il réagir à un <code>ThrottlingException</code> ?",
  choix:["Retry avec backoff EXPONENTIEL et JITTER, en respectant un budget de retry","Retry immédiat en boucle","Abandonner et remonter l'erreur","Basculer sur une autre région"],
  bonne:0,
  explain:"La plupart des API AWS utilisent un seau à jetons. Les erreurs de throttling doivent être observées comme métrique : elles annoncent une saturation avant l'incident visible." },

{ id:"c8-22", lvl:8, dom:"AWS",
  q:"Qu'est-ce qu'une « hot partition » dans DynamoDB ?",
  choix:["Une clé de partition concentre le trafic : throttling alors que la capacité globale semble suffisante","Une partition physiquement défaillante","Une partition trop volumineuse","Une partition en cours de réplication"],
  bonne:0,
  explain:"Parades : clé à haute cardinalité et bien distribuée, suffixe de répartition (write sharding), ou mode on-demand avec adaptive capacity." },

{ id:"c8-23", lvl:8, dom:"AWS",
  q:"Pourquoi une NAT Gateway peut-elle coûter plus cher que le calcul ?",
  choix:["Elle est facturée à l'heure ET au Go traité, y compris vers S3 ou une autre AZ","Elle facture par connexion ouverte","Son prix double en multi-AZ","Elle inclut une licence logicielle"],
  bonne:0,
  explain:"Parades : VPC endpoints (gateway pour S3/DynamoDB, gratuits), registry miroir interne, et vérifier qu'aucun trafic interne ne transite par la NAT à cause d'une route mal placée." },

{ id:"c8-24", lvl:8, dom:"AWS",
  q:"Tu crées un rôle IAM puis l'utilises immédiatement : AccessDenied. Pourquoi ?",
  choix:["IAM est un service global à cohérence à terme : la propagation prend un instant","La policy est mal écrite","Il faut valider le rôle dans la console","Le rôle doit être attaché à un utilisateur d'abord"],
  bonne:0,
  explain:"Parade en automatisation : retry avec backoff après création d'une identité. Cas typique où l'on croit à tort à un bug de permissions." },

{ id:"c8-25", lvl:8, dom:"Azure",
  q:"Quel est le niveau de cohérence par défaut de Cosmos DB ?",
  choix:["Session","Strong","Eventual","Bounded Staleness"],
  bonne:0,
  explain:"Session garantit la cohérence pour la session d'un client — le bon compromis dans la majorité des cas. Strong limite la distribution et coûte en latence et en RU." },

{ id:"c8-26", lvl:8, dom:"Azure",
  q:"Que fait un déploiement ARM en mode « Complete » ?",
  choix:["Il SUPPRIME tout ce qui existe dans le resource group mais n'apparaît pas dans le template","Il déploie toutes les ressources du template","Il valide le template sans déployer","Il déploie en parallèle sur tous les RG"],
  bonne:0,
  explain:"Puissant pour la conformité stricte, catastrophique si le template est incomplet. Le mode Incremental (défaut) ne fait qu'ajouter et mettre à jour." },

{ id:"c8-27", lvl:8, dom:"Azure",
  q:"Après un destroy, recréer un Key Vault du même nom échoue. Pourquoi ?",
  choix:["Le soft delete conserve le nom pendant la période de rétention ; la purge protection empêche même de forcer","Le nom est réservé par un autre tenant","Il faut attendre la réplication géo","Le quota de coffres est atteint"],
  bonne:0,
  explain:"En environnement éphémère, on génère donc des noms uniques. C'est un piège classique en IaC de test." },

{ id:"c8-28", lvl:8, dom:"Réseau",
  q:"Pourquoi une saturation du conntrack provoque-t-elle des pannes « bizarres » ?",
  choix:["Les nouveaux paquets sont DROPPÉS silencieusement : timeouts intermittents alors que CPU et réseau semblent sains","Le noyau redémarre la pile réseau","Les connexions existantes sont coupées d'un coup","Le DNS bascule en TCP"],
  bonne:0,
  explain:"Visible dans <code>dmesg</code> (« nf_conntrack: table full »). On augmente la table, on réduit les timeouts, ou on sort le NAT du chemin." },

{ id:"c8-29", lvl:8, dom:"Réseau",
  q:"Pourquoi un RTT élevé plafonne-t-il le débit TCP ?",
  choix:["Le débit est borné par fenêtre / RTT (bandwidth-delay product), indépendamment de la bande passante achetée","Parce que TCP retransmet plus souvent","Parce que le MTU diminue avec la distance","Parce que le chiffrement coûte plus cher"],
  bonne:0,
  explain:"Paris–Singapour à 200 ms avec une fenêtre de 64 Ko plafonne à ~2,5 Mbit/s. D'où CDN, keep-alive, HTTP/2-3 et réglage des buffers pour les transferts longue distance." },

{ id:"c8-30", lvl:8, dom:"Réseau",
  q:"Quel problème QUIC résout-il par rapport à HTTP/2 ?",
  choix:["Le head-of-line blocking au niveau TCP : les flux deviennent indépendants","La compression des en-têtes","Le multiplexage, absent d'HTTP/2","L'absence de chiffrement"],
  bonne:0,
  explain:"HTTP/3 sur QUIC (UDP) fusionne aussi le handshake avec TLS 1.3 et survit à un changement d'IP. Gain surtout sensible sur mobile et à latence élevée." },

{ id:"c8-31", lvl:8, dom:"Sécurité",
  q:"Qu'apporte la forward secrecy ?",
  choix:["Une compromission FUTURE de la clé privée ne permet pas de déchiffrer les sessions passées","Un chiffrement plus rapide","La révocation instantanée des certificats","L'authentification du client"],
  bonne:0,
  explain:"Chaque session dérive une clé éphémère (ECDHE) jamais transmise. Essentiel pour des données à longue sensibilité, et obligatoire en TLS 1.3." },

{ id:"c8-32", lvl:8, dom:"Sécurité",
  q:"Pourquoi une SSRF est-elle particulièrement dangereuse dans le cloud ?",
  choix:["Elle permet d'atteindre l'endpoint de métadonnées (169.254.169.254) et d'en extraire les credentials du rôle","Elle donne un accès SSH à l'instance","Elle contourne le chiffrement au repos","Elle supprime les logs CloudTrail"],
  bonne:0,
  explain:"Parades : IMDSv2 obligatoire (token + hop limit), validation stricte des URL sortantes, egress filtré." },

{ id:"c8-33", lvl:8, dom:"Sécurité",
  q:"À quoi sert l'<code>ExternalId</code> dans une trust policy AWS cross-compte ?",
  choix:["À prévenir le confused deputy : un tiers ne peut pas être manipulé pour agir sur les ressources d'un autre client","À chiffrer la session STS","À identifier la région d'origine","À prolonger la durée de la session"],
  bonne:0,
  explain:"Complété par les conditions <code>aws:SourceAccount</code> et <code>aws:SourceArn</code> pour les services. Sortir ça en entretien te classe immédiatement." },

{ id:"c8-34", lvl:8, dom:"Observabilité",
  q:"Pourquoi ne jamais mettre un ID utilisateur en label de métrique ?",
  choix:["Chaque combinaison de labels crée une série temporelle : c'est l'explosion de cardinalité","Cela viole le RGPD uniquement","Prometheus refuse les labels numériques","Cela ralentit le scrape"],
  bonne:0,
  explain:"Les labels doivent être de cardinalité BORNÉE (service, méthode, code, région). Le détail unitaire appartient aux logs et aux traces." },

{ id:"c8-35", lvl:8, dom:"Observabilité",
  q:"Qu'apporte l'échantillonnage tail-based par rapport au head-based ?",
  choix:["La décision est prise APRÈS la trace complète : on garde 100 % des erreurs et des requêtes lentes","Il consomme moins de mémoire","Il fonctionne sans collector","Il est plus simple à configurer"],
  bonne:0,
  explain:"En head-based, on décide au premier span sans savoir si la trace sera intéressante — on jette donc des erreurs. Le tail-based exige un collector qui voit tous les spans d'une trace." },

{ id:"c8-36", lvl:8, dom:"SRE",
  q:"Qu'est-ce qu'une défaillance métastable ?",
  choix:["Un état dégradé qui s'auto-entretient même après disparition de la cause initiale","Une panne qui se répare seule","Une panne intermittente sans cause identifiable","Une panne limitée à une zone"],
  bonne:0,
  explain:"Retries, files pleines et caches froids maintiennent la surcharge. Sortie : réduire drastiquement la charge (load shedding) pour casser la boucle, puis remonter progressivement." },

{ id:"c8-37", lvl:8, dom:"SRE",
  q:"Pourquoi ajouter des retries peut-il AGGRAVER une panne ?",
  choix:["Un service qui rame reçoit 3× plus de requêtes et s'effondre — c'est l'amplification","Les retries consomment la bande passante réseau","Les retries invalident le cache","Les retries déclenchent l'autoscaling"],
  bonne:0,
  explain:"Parades : budget de retry global (~10 % du trafic), backoff exponentiel avec JITTER, circuit breaker, timeouts décroissants en profondeur, load shedding." },

{ id:"c8-38", lvl:8, dom:"SQL",
  q:"Sous PostgreSQL, que produit un UPDATE en MVCC ?",
  choix:["Une nouvelle version de la ligne, l'ancienne étant marquée morte — d'où le besoin de VACUUM","Une modification en place de la ligne","Un verrou exclusif sur toute la table","Une réécriture de l'index uniquement"],
  bonne:0,
  explain:"Avantage : les lectures ne bloquent pas les écritures. Contrepartie : bloat, index inefficaces, et à l'extrême un risque de wraparound des transaction IDs." },

{ id:"c8-39", lvl:8, dom:"SQL",
  q:"Un réplica PostgreSQL est arrêté et oublié, avec un replication slot. Que risque le primaire ?",
  choix:["Il conserve les WAL non consommés jusqu'à remplir son disque et s'arrêter","Il bascule automatiquement en lecture seule","Il supprime le slot après 24 h","Rien, le slot expire seul"],
  bonne:0,
  explain:"Piège d'exploitation classique. Parade : <code>max_slot_wal_keep_size</code>, et surveillance des slots inactifs." },

{ id:"c8-40", lvl:8, dom:"Docker",
  q:"Que se passe-t-il quand on écrit dans un fichier d'une couche basse d'une image ?",
  choix:["Un copy-up : le fichier ENTIER est copié dans la couche d'écriture","Le fichier est modifié en place","L'écriture est refusée","Une nouvelle couche d'image est créée"],
  bonne:0,
  explain:"D'où la lenteur des écritures sur de gros fichiers en overlay, et la règle : les données vont dans un volume, pas dans le conteneur." }

]);
