window.QCM = (window.QCM || []).concat([
/* ============ QCM NIVEAU 5 — RÉSEAU, SÉCURITÉ, ÉTAT ============ */

{ id:"c5-01", lvl:5, dom:"Kubernetes",
  q:"Que garantit le modèle réseau CNI de Kubernetes ?",
  choix:["Chaque Pod a sa propre IP et tous les Pods se joignent SANS NAT","Tous les Pods partagent l'IP de leur nœud","Le trafic inter-Pod est chiffré par défaut","Les Pods d'un namespace sont isolés par défaut"],
  bonne:0,
  explain:"Un Pod se voit avec la même IP que les autres le voient. Le plugin (Calico, Cilium, Azure CNI, VPC CNI) implémente ce réseau plat, par overlay ou par routage natif." },

{ id:"c5-02", lvl:5, dom:"Kubernetes",
  q:"Quel est le comportement par défaut du trafic entre Pods, sans NetworkPolicy ?",
  choix:["Tout est autorisé, y compris entre namespaces","Tout est bloqué jusqu'à autorisation explicite","Seul le trafic intra-namespace est permis","Cela dépend du cloud provider"],
  bonne:0,
  explain:"Dès qu'une NetworkPolicy sélectionne un Pod pour une direction, tout ce qui n'est pas explicitement autorisé DANS CETTE DIRECTION devient interdit. Bonne pratique : default-deny par namespace." },

{ id:"c5-03", lvl:5, dom:"Kubernetes",
  q:"Ton HPA ne fait rien du tout. Quelle est la cause la plus fréquente ?",
  choix:["Les <code>resources.requests</code> ne sont pas définies : impossible de calculer un pourcentage","Le Deployment a trop de réplicas","Le namespace n'a pas de quota","Le HPA nécessite un service mesh"],
  bonne:0,
  explain:"Le HPA compare l'usage à la cible en % des <b>requests</b>. Autre prérequis : le metrics-server doit être installé." },

{ id:"c5-04", lvl:5, dom:"Kubernetes",
  q:"Quel autoscaler ajoute des NŒUDS au cluster ?",
  choix:["Le Cluster Autoscaler, déclenché par des Pods Pending","Le HPA","Le VPA","KEDA"],
  bonne:0,
  explain:"HPA = plus de Pods. VPA = ajuste les requests d'un Pod (et le redémarre). KEDA = réplicas sur événement, avec scale-to-zero. HPA + Cluster Autoscaler se complètent parfaitement." },

{ id:"c5-05", lvl:5, dom:"Kubernetes",
  q:"Que fait <code>kubectl drain</code> avant d'évincer les Pods ?",
  choix:["Il cordonne le nœud, puis évince en respectant les PodDisruptionBudgets","Il sauvegarde les volumes","Il migre les Pods à chaud sans redémarrage","Il supprime le nœud du cluster"],
  bonne:0,
  explain:"Précautions : capacité disponible ailleurs, PDB définis, <code>--ignore-daemonsets</code>, et <code>--delete-emptydir-data</code> seulement si on accepte de perdre ces données." },

{ id:"c5-06", lvl:5, dom:"Kubernetes",
  q:"Quel accessMode permet à plusieurs nœuds de monter le même volume en écriture ?",
  choix:["ReadWriteMany (NFS, EFS, Azure Files)","ReadWriteOnce","ReadOnlyMany","ReadWriteOncePod"],
  bonne:0,
  explain:"Un disque bloc (EBS, Azure Disk) est ReadWriteOnce : un seul nœud à la fois. D'où les erreurs « Multi-Attach » quand un Pod veut démarrer ailleurs avant le détachement." },

{ id:"c5-07", lvl:5, dom:"Kubernetes",
  q:"Comment un Pod EKS obtient-il des droits AWS sans clé statique ?",
  choix:["IRSA : provider OIDC + rôle IAM dont la trust policy accepte le ServiceAccount, annoté avec l'ARN","En montant les credentials de l'instance","Via un Secret Kubernetes contenant la clé","Par une NetworkPolicy vers l'API AWS"],
  bonne:0,
  explain:"Le SDK obtient des credentials temporaires par <code>AssumeRoleWithWebIdentity</code>. Droits par APPLICATION et non par nœud — c'est la différence clé avec l'instance profile." },

{ id:"c5-08", lvl:5, dom:"Terraform",
  q:"Comment détecter industriellement la dérive (drift) ?",
  choix:["<code>terraform plan -detailed-exitcode</code> planifié en CI (code 2 = changements)","<code>terraform validate</code> quotidien","En comparant les fichiers .tf entre eux","En relisant les logs CloudTrail à la main"],
  bonne:0,
  explain:"La vraie solution est en amont : retirer les droits d'écriture manuels en production. La détection ne fait que constater." },

{ id:"c5-09", lvl:5, dom:"Terraform",
  q:"Pourquoi éviter <code>terraform_remote_state</code> pour lire une valeur d'un autre state ?",
  choix:["Il exige un droit de lecture sur TOUT le state distant, donc sur ses secrets, et crée un couplage fort","Il est déprécié","Il ne fonctionne qu'avec le backend S3","Il ralentit le plan de 30 secondes"],
  bonne:0,
  explain:"Alternative préférable en banque : publier la valeur dans une source de vérité (SSM Parameter, Key Vault, tag) et la lire avec une data source — droits fins, découplage." },

{ id:"c5-10", lvl:5, dom:"Terraform",
  q:"Comment gérer deux régions dans une même configuration ?",
  choix:["Des providers aliasés (<code>alias = \"us\"</code>) référencés par <code>provider = aws.us</code>","Deux blocs backend","Une variable region avec une boucle for_each sur le provider","Deux fichiers .tfvars"],
  bonne:0,
  explain:"Cas typique : un certificat ACM pour CloudFront doit être créé dans us-east-1. Les modules reçoivent les providers via <code>providers = { … }</code>." },

{ id:"c5-11", lvl:5, dom:"Terraform",
  q:"Quel outil vérifie la conformité de l'infrastructure AVANT création ?",
  choix:["OPA/Conftest, Sentinel ou Checkov appliqués sur le plan JSON","terraform fmt","terraform refresh","Le linter du provider"],
  bonne:0,
  explain:"C'est le contrôle le moins cher. Mais il ne suffit pas : il faut aussi une admission côté plateforme (Azure Policy, SCP, Kyverno) pour ce qui contournerait le pipeline." },

{ id:"c5-12", lvl:5, dom:"AWS",
  q:"À quoi sert une dead-letter queue ?",
  choix:["Isoler les messages en échec après N tentatives, pour ne pas bloquer le traitement","Archiver les messages traités","Chiffrer les messages sensibles","Prioriser les messages urgents"],
  bonne:0,
  explain:"Sans DLQ, un message « poison » est redélivré indéfiniment. Il faut aussi ALERTER sur la profondeur de la DLQ : une DLQ que personne ne regarde est une perte de données silencieuse." },

{ id:"c5-13", lvl:5, dom:"AWS",
  q:"Quelle est la différence fonctionnelle entre SQS et SNS ?",
  choix:["SQS = file consommée en pull, un message traité une fois ; SNS = pub/sub en push vers plusieurs abonnés","SQS est synchrone, SNS asynchrone","SNS garantit l'ordre, pas SQS","SQS ne fonctionne qu'avec Lambda"],
  bonne:0,
  explain:"Le fan-out combine les deux : SNS publie vers PLUSIEURS files SQS, chacune consommée par un service indépendant à son rythme." },

{ id:"c5-14", lvl:5, dom:"AWS",
  q:"Comment réduire un cold start Lambda ?",
  choix:["Package léger, dépendances hors du handler, plus de mémoire, Provisioned Concurrency si nécessaire","Augmenter le timeout","Désactiver le VPC","Utiliser un runtime plus ancien"],
  bonne:0,
  explain:"Plus de mémoire = plus de CPU alloué, donc init plus rapide. La Provisioned Concurrency garde des environnements chauds, au prix d'un coût fixe." },

{ id:"c5-15", lvl:5, dom:"AWS",
  q:"Lequel répond à « qui a fait quel appel API, quand et depuis où » ?",
  choix:["CloudTrail","CloudWatch","AWS Config","GuardDuty"],
  bonne:0,
  explain:"CloudWatch = métriques, logs, alarmes. AWS Config = état et historique de CONFIGURATION avec règles de conformité. Distinction classique en environnement régulé." },

{ id:"c5-16", lvl:5, dom:"Azure",
  q:"Quel niveau de redondance réplique dans la région appairée ?",
  choix:["GRS","LRS","ZRS","Aucun"],
  bonne:0,
  explain:"LRS = 3 copies dans un datacenter. ZRS = 3 zones de la région. GRS = LRS + réplication asynchrone géo. GZRS = ZRS + géo. Les variantes RA-* permettent de lire le secondaire." },

{ id:"c5-17", lvl:5, dom:"Azure",
  q:"Dans quel cas une UDR est-elle indispensable ?",
  choix:["Pour forcer le trafic d'un spoke vers l'IP privée du firewall du hub (next hop Virtual Appliance)","Pour attribuer une IP publique à une VM","Pour activer les Private Endpoints","Pour autoriser le trafic entre deux subnets"],
  bonne:0,
  explain:"L'UDR surcharge le routage système d'Azure. Autre cas : le forced tunneling vers l'on-premise via ExpressRoute — exigence courante en banque." },

{ id:"c5-18", lvl:5, dom:"Azure",
  q:"Qu'est-ce que KQL ?",
  choix:["Le langage de requête de Log Analytics et Azure Monitor","Un format de fichier de configuration Azure","Le protocole de Key Vault","Un type de base de données Cosmos"],
  bonne:0,
  explain:"Exemple : <code>AzureDiagnostics | where TimeGenerated &gt; ago(1h) | summarize count() by ResourceId</code>. Il alimente aussi les alertes, les workbooks et Azure Resource Graph." },

{ id:"c5-19", lvl:5, dom:"Azure",
  q:"Quel est le principal inconvénient d'Azure CNI par rapport à Kubenet ?",
  choix:["Chaque Pod consomme une IP DU VNET : il faut dimensionner le subnet en conséquence","Il ne supporte pas les NetworkPolicy","Il est plus lent","Il ne fonctionne pas avec les Private Endpoints"],
  bonne:0,
  explain:"Dimensionnement : nœuds × (max pods par nœud + 1). Un sous-dimensionnement bloque la montée en charge et ne se corrige pas à chaud. Azure CNI Overlay est le compromis moderne." },

{ id:"c5-20", lvl:5, dom:"Réseau",
  q:"Quelle est la différence entre un proxy et un reverse proxy ?",
  choix:["Le proxy est côté client pour le trafic sortant ; le reverse proxy est côté serveur pour le trafic entrant","Le reverse proxy chiffre, le proxy non","Le proxy fonctionne en L4, le reverse proxy en L7","Aucune, c'est une question de configuration"],
  bonne:0,
  explain:"Le proxy d'entreprise (sortant, filtrage, inspection TLS) est obligatoire en banque — pensez à <code>HTTP_PROXY</code>/<code>NO_PROXY</code> et à la CA interne dans les conteneurs." },

{ id:"c5-21", lvl:5, dom:"Réseau",
  q:"Deux VPC sont peerés mais A ne joint pas C via B. Pourquoi ?",
  choix:["Le peering n'est pas transitif : il faut un Transit Gateway","Les CIDR sont trop grands","Le peering met 24 h à se propager","Il manque une NAT Gateway"],
  bonne:0,
  explain:"Autres vérifications sur un peering : accepté des deux côtés, routes présentes dans LES DEUX route tables, CIDR non chevauchants, SG/NACL ouverts dans les deux sens." },

{ id:"c5-22", lvl:5, dom:"Réseau",
  q:"Pourquoi l'IP source change-t-elle en sortie d'un VPC via NAT Gateway ?",
  choix:["Le NAT fait du Source NAT : l'IP privée est remplacée par l'IP publique du NAT","Le routeur anonymise le trafic pour la sécurité","L'IP privée n'est pas routable donc elle est supprimée","C'est un comportement propre à AWS"],
  bonne:0,
  explain:"Conséquence pratique : côté partenaire, c'est l'IP du NAT qu'il faut autoriser en liste blanche, pas celle de l'instance." },

{ id:"c5-23", lvl:5, dom:"Sécurité",
  q:"Le payload d'un JWT est-il chiffré ?",
  choix:["Non : il est signé, donc lisible par tous. Jamais de secret dedans","Oui, avec la clé du serveur","Oui, si l'algorithme est RS256","Cela dépend de l'émetteur"],
  bonne:0,
  explain:"Erreurs classiques : ne pas vérifier la signature, accepter <code>alg: none</code>, ne pas valider <code>exp</code>/<code>aud</code>/<code>iss</code>, et croire qu'on peut révoquer un JWT." },

{ id:"c5-24", lvl:5, dom:"Sécurité",
  q:"Pourquoi la rotation de secrets ne suffit-elle pas ?",
  choix:["Elle limite la fenêtre d'exploitation mais ne détecte pas la fuite","Elle est trop lente à automatiser","Elle casse les applications en production","Elle n'est pas exigée par les auditeurs"],
  bonne:0,
  explain:"Il faut aussi la détection de secrets dans le code, la journalisation des accès au coffre, l'alerte sur usage anormal — et surtout supprimer les secrets longue durée au profit de l'identité fédérée." },

{ id:"c5-25", lvl:5, dom:"Sécurité",
  q:"Quelle parade rend le contrôle des images NON contournable ?",
  choix:["Une politique d'admission (Kyverno, Gatekeeper) qui rejette les images non signées ou hors registry approuvé","Un scan bloquant en CI","Une revue de code obligatoire","Un registry privé"],
  bonne:0,
  explain:"La CI seule ne suffit jamais : quelqu'un finira par déployer hors pipeline. L'admission est la dernière barrière — elle ne remplace pas la CI, elle la rend obligatoire." },

{ id:"c5-26", lvl:5, dom:"Sécurité",
  q:"Qu'est-ce qu'une attaque de la chaîne d'approvisionnement sur une image de conteneur ?",
  choix:["La compromission d'un maillon amont : image de base, paquet typosquatté, action de CI tierce non épinglée","Un déni de service sur le registry","Le vol des credentials du registry","Une injection SQL dans l'application"],
  bonne:0,
  explain:"Parades : registry miroir avec bases approuvées, pin par digest, SBOM et scan continu, signature Cosign vérifiée à l'admission, attestations de provenance (SLSA)." },

{ id:"c5-27", lvl:5, dom:"Observabilité",
  q:"Prometheus fonctionne en push ou en pull ?",
  choix:["En pull : il scrape des endpoints /metrics découverts par service discovery","En push : les applications envoient leurs métriques","Les deux au choix","En pull pour les métriques, en push pour les logs"],
  bonne:0,
  explain:"Avantage du pull : il sait qui ne répond plus (<code>up == 0</code>). Pour les jobs batch qui meurent avant le scrape, on passe par le Pushgateway — avec parcimonie." },

{ id:"c5-28", lvl:5, dom:"Observabilité",
  q:"Pourquoi ne peut-on pas moyenner des p95 de plusieurs instances ?",
  choix:["Les percentiles ne sont pas additifs : il faut agréger les buckets bruts de l'histogramme","Parce que les instances ont des charges différentes","Parce que Prometheus l'interdit","On peut, c'est une bonne pratique"],
  bonne:0,
  explain:"D'où <code>histogram_quantile(0.95, sum(rate(..._bucket[5m])) by (le))</code>, qui agrège les buckets AVANT de calculer le quantile." },

{ id:"c5-29", lvl:5, dom:"Observabilité",
  q:"Pourquoi un compteur Prometheus s'utilise-t-il toujours avec <code>rate()</code> ?",
  choix:["Sa valeur brute cumulée n'a pas de sens ; <code>rate()</code> donne la variation par seconde et gère les redémarrages","Parce que <code>rate()</code> est plus rapide","Pour convertir en pourcentage","Pour lisser les pics"],
  bonne:0,
  explain:"« 4 823 191 requêtes depuis le démarrage » n'informe personne. <code>rate()</code> gère automatiquement les remises à zéro lors d'un redémarrage du process." },

{ id:"c5-30", lvl:5, dom:"SQL",
  q:"Quel niveau d'isolation empêche les lectures non répétables mais autorise encore les phantom reads ?",
  choix:["Repeatable Read","Read Committed","Read Uncommitted","Serializable"],
  bonne:0,
  explain:"Progression : Read Uncommitted (lectures sales) → Read Committed (lectures non répétables) → Repeatable Read (phantoms) → Serializable (tout empêché, au prix de la concurrence)." },

{ id:"c5-31", lvl:5, dom:"SQL",
  q:"Quelle est la première étape pour diagnostiquer une requête lente ?",
  choix:["<code>EXPLAIN ANALYZE</code> pour lire le plan d'exécution réel","Ajouter un index sur toutes les colonnes du WHERE","Augmenter la RAM du serveur","Passer en isolation Read Uncommitted"],
  bonne:0,
  explain:"On cherche : seq scan sur grosse table, estimation de lignes très éloignée du réel (statistiques périmées), mauvais ordre de jointure, tri sur disque." },

{ id:"c5-32", lvl:5, dom:"SRE",
  q:"Que fait un circuit breaker après N échecs ?",
  choix:["Il OUVRE le circuit et fait échouer immédiatement les appels, puis teste périodiquement (half-open)","Il redémarre le service défaillant","Il redirige vers un autre datacenter","Il met les requêtes en file d'attente"],
  bonne:0,
  explain:"Sans lui, les threads s'accumulent en attente de timeout et la panne d'un service en profondeur remonte en cascade jusqu'au front — mode de défaillance numéro un des microservices." },

{ id:"c5-33", lvl:5, dom:"SRE",
  q:"Qu'est-ce qu'une dégradation gracieuse ?",
  choix:["Le service rend l'essentiel en désactivant l'accessoire, au lieu de tomber entièrement","Une baisse progressive des performances","L'arrêt planifié d'un service","Le passage automatique en lecture seule"],
  bonne:0,
  explain:"Exemple bancaire : si le scoring temps réel est indisponible, on continue d'afficher solde et historique en désactivant les recommandations. Cela suppose d'avoir hiérarchisé les fonctions AVANT l'incident." },

{ id:"c5-34", lvl:5, dom:"Docker",
  q:"Qu'apporte BuildKit pour les secrets ?",
  choix:["<code>--mount=type=secret</code> : le secret est disponible pendant le RUN sans rester dans les couches","Il chiffre les couches de l'image","Il stocke les secrets dans le registry","Il génère automatiquement des secrets éphémères"],
  bonne:0,
  explain:"BuildKit apporte aussi la parallélisation du graphe, le cache exportable entre machines (crucial pour des runners éphémères) et les builds multi-plateformes." },

{ id:"c5-35", lvl:5, dom:"CI/CD",
  q:"Comment exécuter des migrations de base dans un déploiement Kubernetes ?",
  choix:["Un Job (ou hook Helm pre-upgrade) en UNE seule instance, avant le rollout","Un initContainer sur chaque Pod","Dans le CMD du conteneur principal","Manuellement après le déploiement"],
  bonne:0,
  explain:"Un initContainer sur N réplicas = N migrations simultanées : anti-pattern. L'outil de migration (Flyway, Liquibase) pose en plus un verrou en base." }

]);
