window.QCM = (window.QCM || []).concat([
/* ============ QCM NIVEAU 4 — INTERMÉDIAIRE ============ */

{ id:"c4-01", lvl:4, dom:"Kubernetes",
  q:"Dans quel ordre se déroule un <code>kubectl apply</code> ?",
  choix:["API server (authN, RBAC, admission) → etcd → controller crée le ReplicaSet → scheduler assigne un nœud → kubelet démarre les conteneurs","Scheduler → API server → kubelet → etcd","kubelet → etcd → API server → controller","etcd → scheduler → API server → kubelet"],
  bonne:0,
  explain:"Tout passe par l'API server, seule porte d'entrée. Les webhooks mutating s'exécutent avant les validating, et etcd n'est écrit qu'après validation." },

{ id:"c4-02", lvl:4, dom:"Kubernetes",
  q:"Que règle <code>maxUnavailable: 0</code> combiné à <code>maxSurge: 1</code> ?",
  choix:["Aucune perte de capacité pendant le rollout, mais il faut de la marge sur le cluster","Le déploiement le plus rapide possible","Un déploiement blue/green","La désactivation du rolling update"],
  bonne:0,
  explain:"maxSurge = combien de Pods EN PLUS on autorise temporairement ; maxUnavailable = combien peuvent manquer. À 0/1, on ajoute avant de retirer." },

{ id:"c4-03", lvl:4, dom:"Kubernetes",
  q:"Contre quoi un PodDisruptionBudget ne protège-t-il PAS ?",
  choix:["Les disruptions involontaires : crash de nœud, OOMKill, panne matérielle","Les drains de nœud","Les upgrades de node pool","Le scale-down de l'autoscaler"],
  bonne:0,
  explain:"Le PDB ne couvre que les disruptions VOLONTAIRES. Sans lui, un upgrade de node pool peut vider ton service entier ; avec lui, un crash matériel reste un crash." },

{ id:"c4-04", lvl:4, dom:"Kubernetes",
  q:"Quelle est la différence entre un taint et une nodeAffinity ?",
  choix:["Le taint est une répulsion posée par le NŒUD ; la nodeAffinity est une attraction exprimée par le POD","Le taint concerne le CPU, l'affinity la mémoire","Le taint est temporaire, l'affinity est permanente","Ce sont deux syntaxes du même mécanisme"],
  bonne:0,
  explain:"Les deux se combinent : la toleration AUTORISE le Pod à aller sur un nœud tainté, l'affinity le DIRIGE vers le bon type de nœud." },

{ id:"c4-05", lvl:4, dom:"Kubernetes",
  q:"Quel est le FQDN complet d'un Service <code>api</code> dans le namespace <code>prod</code> ?",
  choix:["<code>api.prod.svc.cluster.local</code>","<code>prod.api.cluster.local</code>","<code>api.cluster.local/prod</code>","<code>svc.api.prod.local</code>"],
  bonne:0,
  explain:"Résolu par CoreDNS. Depuis le même namespace, le nom court suffit grâce à la liste <code>search</code> du resolv.conf injecté par le kubelet." },

{ id:"c4-06", lvl:4, dom:"Kubernetes",
  q:"Tu crées un objet Ingress mais rien ne route. Pourquoi ?",
  choix:["Un Ingress n'est qu'une déclaration : il faut un Ingress Controller pour l'appliquer","Il manque un Service de type LoadBalancer","Le namespace n'est pas annoté","L'Ingress met 24 h à se propager"],
  bonne:0,
  explain:"Le controller (ingress-nginx, Traefik, AGIC, ALB Controller) surveille les objets Ingress et configure un vrai reverse proxy. La Gateway API en est le successeur normalisé." },

{ id:"c4-07", lvl:4, dom:"Kubernetes",
  q:"Comment donner à un Pod le droit d'appeler l'API Kubernetes sans excès de privilèges ?",
  choix:["Un ServiceAccount dédié + un Role limité aux verbes nécessaires, lié par un RoleBinding","Lui donner le rôle cluster-admin puis restreindre par NetworkPolicy","Utiliser le ServiceAccount default du namespace","Monter le kubeconfig de l'administrateur"],
  bonne:0,
  explain:"Jamais le SA <code>default</code>, jamais <code>cluster-admin</code>. Et <code>automountServiceAccountToken: false</code> quand le Pod n'appelle pas l'API du tout." },

{ id:"c4-08", lvl:4, dom:"Kubernetes",
  q:"À quoi sert un sidecar ?",
  choix:["Un conteneur secondaire du même Pod : proxy de mesh, collecteur de logs, rechargeur de config","À remplacer le conteneur principal en cas de crash","À exécuter une tâche avant le démarrage","À répliquer le Pod sur un autre nœud"],
  bonne:0,
  explain:"Il partage réseau et volumes avec le conteneur principal. Coût : des ressources par Pod et un ordre d'arrêt à gérer — les <em>native sidecars</em> règlent ce dernier point." },

{ id:"c4-09", lvl:4, dom:"Terraform",
  q:"Que fait <code>terraform state rm</code> ?",
  choix:["Il retire la ressource du state SANS la détruire dans le cloud","Il détruit la ressource et l'enlève du state","Il supprime le fichier de state","Il annule le dernier apply"],
  bonne:0,
  explain:"Terraform cesse simplement de la gérer. Usage : migrer une ressource vers un autre state, ou abandonner sa gestion. Si le code la référence encore, le prochain apply voudra la recréer." },

{ id:"c4-10", lvl:4, dom:"Terraform",
  q:"Pourquoi préférer un bloc <code>moved</code> à <code>terraform state mv</code> ?",
  choix:["Il est versionné, revu en PR, visible dans le plan et rejoué automatiquement par tous","Il est plus rapide","<code>state mv</code> est déprécié","Il fonctionne sans backend distant"],
  bonne:0,
  explain:"<code>state mv</code> est une commande manuelle qu'il faudrait reproduire sur chaque poste et dans la CI. Le bloc <code>moved</code> déclare le refactoring dans le CODE." },

{ id:"c4-11", lvl:4, dom:"Terraform",
  q:"Que fait <code>create_before_destroy</code> ?",
  choix:["Crée le remplaçant avant de supprimer l'ancien, pour éviter la coupure","Empêche toute destruction de la ressource","Ignore les modifications faites hors Terraform","Crée une sauvegarde avant destruction"],
  bonne:0,
  explain:"Attention aux noms uniques : la ressource de remplacement ne peut pas porter le même nom que celle encore existante. <code>prevent_destroy</code> et <code>ignore_changes</code> répondent à d'autres besoins." },

{ id:"c4-12", lvl:4, dom:"Terraform",
  q:"Que ne doit JAMAIS contenir un module Terraform réutilisable ?",
  choix:["Un bloc <code>provider</code> ou <code>backend</code> — ils appartiennent au root module","Des outputs","Des variables avec validation","Des locals"],
  bonne:0,
  explain:"Un module qui définit son propre provider ne peut plus être supprimé proprement. Il les REÇOIT via <code>providers = { aws = aws.eu }</code>." },

{ id:"c4-13", lvl:4, dom:"AWS",
  q:"Un rôle a <code>s3:GetObject</code> mais l'appel échoue en AccessDenied. Cause la plus probable si l'objet est chiffré ?",
  choix:["Il manque <code>kms:Decrypt</code> sur la clé KMS","Le bucket est dans une autre région","L'objet est en classe Glacier","La policy doit être attachée à un user, pas à un rôle"],
  bonne:0,
  explain:"Autres suspects : un Deny explicite (bucket policy, SCP, boundary), Block Public Access, ou une condition non satisfaite. On tranche avec le Policy Simulator et CloudTrail." },

{ id:"c4-14", lvl:4, dom:"AWS",
  q:"Dans l'évaluation d'une décision IAM, qu'est-ce qui l'emporte toujours ?",
  choix:["Un Deny explicite","Un Allow explicite dans une identity policy","La policy la plus récente","La policy attachée au plus près de la ressource"],
  bonne:0,
  explain:"1) Deny par défaut. 2) Un Deny explicite arrête l'évaluation. 3) Sinon il faut un Allow dans l'intersection SCP ∩ boundary ∩ identity policy (ou une resource policy)." },

{ id:"c4-15", lvl:4, dom:"AWS",
  q:"Quelle est la différence entre RDS Multi-AZ et un Read Replica ?",
  choix:["Multi-AZ = haute disponibilité (réplication synchrone, bascule auto) ; Read Replica = montée en charge en lecture (asynchrone)","Multi-AZ permet de lire sur le standby","Read Replica bascule automatiquement en cas de panne","Ce sont deux noms du même mécanisme"],
  bonne:0,
  explain:"Question très discriminante. Le standby Multi-AZ n'est pas lisible (sur RDS classique) : il sert uniquement à la disponibilité." },

{ id:"c4-16", lvl:4, dom:"AWS",
  q:"Quel VPC Endpoint est gratuit et s'ajoute comme une route ?",
  choix:["Le Gateway endpoint (S3 et DynamoDB uniquement)","L'Interface endpoint (PrivateLink)","Les deux sont gratuits","Aucun, tous sont facturés à l'heure"],
  bonne:0,
  explain:"L'Interface endpoint crée une ENI avec IP privée dans ton subnet et se facture à l'heure ET au Go — mais il couvre la plupart des services." },

{ id:"c4-17", lvl:4, dom:"Azure",
  q:"Comment une App Service accède-t-elle à un Key Vault sans stocker de secret ?",
  choix:["Managed Identity + rôle Key Vault Secrets User, puis référence <code>@Microsoft.KeyVault(SecretUri=…)</code>","En stockant la clé du coffre dans les app settings","Via une chaîne de connexion chiffrée","En montant le coffre comme un volume"],
  bonne:0,
  explain:"Aucun secret dans le code ni dans la configuration. C'est le schéma attendu sur toute question de gestion de secrets côté Azure." },

{ id:"c4-18", lvl:4, dom:"Azure",
  q:"Quel est le piège classique lors d'un swap de deployment slot ?",
  choix:["Par défaut les app settings SUIVENT le swap : il faut cocher « deployment slot setting » sur ce qui est spécifique à l'environnement","Le swap provoque toujours une coupure de service","Les slots ne partagent pas le même plan","Le rollback après swap est impossible"],
  bonne:0,
  explain:"Sinon la préproduction récupère les chaînes de connexion de production, et inversement. Le retour arrière se fait en re-swappant." },

{ id:"c4-19", lvl:4, dom:"Azure",
  q:"Un Global Administrator Entra ID a-t-il par défaut des droits sur les ressources Azure ?",
  choix:["Non : Entra ID gère l'annuaire, Azure RBAC gère les ressources — il doit activer « Elevate access »","Oui, il a tous les droits partout","Oui, mais seulement en lecture","Seulement sur les subscriptions qu'il a créées"],
  bonne:0,
  explain:"Deux plans distincts. C'est une question de niveau senior qui piège beaucoup de candidats." },

{ id:"c4-20", lvl:4, dom:"Azure",
  q:"Dans une topologie hub-and-spoke, que met-on dans le hub ?",
  choix:["Azure Firewall, VPN/ExpressRoute Gateway, Bastion, DNS privé","Les applications les plus critiques","Les bases de données de production","Les environnements de développement"],
  bonne:0,
  explain:"Les spokes ne se parlent pas directement : on force le transit par le hub via des UDR pour inspecter le trafic. C'est le modèle standard des landing zones bancaires." },

{ id:"c4-21", lvl:4, dom:"CI/CD",
  q:"Quel est le coût principal d'un déploiement blue/green par rapport à un canary ?",
  choix:["Il faut payer la double capacité pendant la bascule","Il est impossible de revenir en arrière","Il exige deux bases de données","Il ne fonctionne pas avec des conteneurs"],
  bonne:0,
  explain:"Blue/green : bascule totale, rollback instantané, double capacité. Canary : montée progressive selon les métriques, moins cher, mais plus long et deux versions coexistent." },

{ id:"c4-22", lvl:4, dom:"CI/CD",
  q:"Comment déployer sans coupure une migration de base incompatible ?",
  choix:["Pattern expand/contract : ajouter, écrire dans les deux, migrer, puis seulement supprimer","Mettre l'application en maintenance le temps de la migration","Faire la migration après le déploiement du nouveau code","Utiliser une transaction unique très longue"],
  bonne:0,
  explain:"L'ancienne version doit continuer de fonctionner pendant tout le rollout — c'est aussi ce qui rend le rollback possible. Jamais de migration destructive dans le même déploiement que le code." },

{ id:"c4-23", lvl:4, dom:"CI/CD",
  q:"Que fait-on d'un test flaky ?",
  choix:["On le met en quarantaine hors du pipeline bloquant, on ouvre un ticket et on corrige la cause","On le relance jusqu'à ce qu'il passe","On le supprime définitivement","On augmente son timeout"],
  bonne:0,
  explain:"Causes : dépendance au temps, à l'ordre d'exécution, au réseau, à un état partagé. Un pipeline qu'on relance « pour voir » a perdu toute valeur de signal." },

{ id:"c4-24", lvl:4, dom:"Linux",
  q:"Quel mécanisme LIMITE la consommation de ressources d'un conteneur ?",
  choix:["Les cgroups","Les namespaces","Les capabilities","Le système de fichiers overlay"],
  bonne:0,
  explain:"Les namespaces isolent ce que le processus VOIT (pid, net, mnt, uts, ipc, user). Les cgroups limitent ce qu'il CONSOMME (cpu, memory, io, pids)." },

{ id:"c4-25", lvl:4, dom:"Linux",
  q:"Comment vérifier que ton application a été tuée par l'OOM killer ?",
  choix:["<code>dmesg -T | grep -i oom</code> ou <code>journalctl -k</code>","Dans les logs applicatifs","Avec <code>top</code>","Avec <code>df -h</code>"],
  bonne:0,
  explain:"Le noyau logue « Out of memory: Killed process ». Côté conteneur : exit code 137 et <code>OOMKilled</code> dans <code>kubectl describe</code>." },

{ id:"c4-26", lvl:4, dom:"Réseau",
  q:"Un client obtient un TIMEOUT plutôt qu'un « connection refused ». Que suspectes-tu ?",
  choix:["Un firewall qui DROP silencieusement, ou une route absente","Un service qui n'écoute pas sur le port","Un certificat TLS expiré","Une erreur DNS"],
  bonne:0,
  explain:"DROP = pas de réponse, le client attend. REJECT = RST ou ICMP unreachable, refus immédiat. Donc : timeout → SG/NSG/NACL ou routage ; refused → rien n'écoute." },

{ id:"c4-27", lvl:4, dom:"Réseau",
  q:"Symptôme signature d'un MTU mal réglé sur un tunnel VPN ?",
  choix:["Les petites requêtes passent, les gros transferts se figent","Toutes les connexions échouent","La latence double uniformément","Le DNS ne résout plus"],
  bonne:0,
  explain:"Les paquets pleins nécessitent une fragmentation refusée, souvent parce que l'ICMP « fragmentation needed » est bloqué : le PMTUD est cassé." },

{ id:"c4-28", lvl:4, dom:"Sécurité",
  q:"Qu'est-ce que mTLS apporte par rapport à TLS classique ?",
  choix:["Le CLIENT présente aussi un certificat : authentification mutuelle","Un chiffrement plus fort","Une compression du trafic","Une meilleure performance"],
  bonne:0,
  explain:"On l'impose entre services internes (service mesh, zero trust) ou avec des API partenaires. Coût : une PKI et une rotation de certificats à industrialiser." },

{ id:"c4-29", lvl:4, dom:"Sécurité",
  q:"Qu'est-ce qu'OpenID Connect ajoute à OAuth 2.0 ?",
  choix:["Une couche d'AUTHENTIFICATION avec un <code>id_token</code> décrivant l'utilisateur","Le chiffrement des tokens","La révocation automatique","La gestion des rôles"],
  bonne:0,
  explain:"OAuth 2.0 est un protocole d'AUTORISATION (déléguer un accès). Utiliser OAuth seul pour authentifier est une erreur de conception classique." },

{ id:"c4-30", lvl:4, dom:"Sécurité",
  q:"À quoi sert une permission boundary AWS ?",
  choix:["Plafonner les droits d'une identité : les permissions effectives sont l'INTERSECTION policy ∩ boundary","Interdire l'accès depuis certaines IP","Limiter la durée d'une session","Chiffrer les credentials"],
  bonne:0,
  explain:"Usage typique : laisser des équipes créer leurs propres rôles IAM sans qu'elles puissent s'octroyer plus que la boundary — délégation encadrée." },

{ id:"c4-31", lvl:4, dom:"Observabilité",
  q:"Que mesure la méthode RED ?",
  choix:["Rate, Errors, Duration — l'expérience côté service","Resources, Efficiency, Downtime","Read, Execute, Delete","Reliability, Endurance, Density"],
  bonne:0,
  explain:"RED répond à « mes utilisateurs souffrent-ils ? ». USE (Utilization, Saturation, Errors) répond à « quelle ressource est le goulot ? »." },

{ id:"c4-32", lvl:4, dom:"Observabilité",
  q:"Pourquoi regarder le p99 plutôt que la moyenne de latence ?",
  choix:["La moyenne masque la queue : 99 requêtes à 50 ms et une à 10 s donnent une moyenne rassurante","Le p99 est plus facile à calculer","La moyenne n'est pas supportée par Prometheus","Le p99 est exigé par les SLA"],
  bonne:0,
  explain:"Sur une page qui fait 20 appels, le p99 de chaque appel devient l'expérience normale d'un utilisateur. Et on ne moyenne jamais des percentiles : ils ne sont pas additifs." },

{ id:"c4-33", lvl:4, dom:"SRE",
  q:"Que signifie RPO ?",
  choix:["Le volume de données qu'on accepte de perdre","Le temps nécessaire pour rétablir le service","Le nombre de réplicas minimum","Le pourcentage de disponibilité garanti"],
  bonne:0,
  explain:"RTO = en combien de temps on revient. RPO = combien de données on perd. Un RPO proche de zéro impose de la réplication synchrone, donc du coût et de la latence." },

{ id:"c4-34", lvl:4, dom:"SQL",
  q:"Comment évite-t-on structurellement les deadlocks ?",
  choix:["Accéder aux ressources toujours dans le MÊME ordre et garder les transactions courtes","Augmenter le timeout de verrouillage","Passer en isolation Serializable","Supprimer les index"],
  bonne:0,
  explain:"Un deadlock, c'est deux transactions qui s'attendent mutuellement ; le SGBD en tue une et l'application doit rejouer. Indexer aide aussi : on verrouille des lignes plutôt que des plages." },

{ id:"c4-35", lvl:4, dom:"SQL",
  q:"Pourquoi <code>OFFSET 100000</code> est-il lent pour paginer ?",
  choix:["La base doit parcourir puis jeter 100 000 lignes ; le coût croît avec la page","Il verrouille toute la table","Il désactive les index","Il n'est pas supporté par PostgreSQL"],
  bonne:0,
  explain:"On préfère la pagination par clé (keyset/seek) : <code>WHERE (created_at, id) &lt; (:date, :id) ORDER BY … LIMIT 50</code>, à coût constant avec un index adapté." }

]);
