window.QCM = (window.QCM || []).concat([
/* ============ QCM NIVEAU 6 — TROUBLESHOOTING ============ */

{ id:"c6-01", lvl:6, dom:"Kubernetes",
  q:"Un Service ne route vers aucun Pod. Quelle est la PREMIÈRE vérification ?",
  choix:["<code>kubectl get endpoints &lt;svc&gt;</code> : s'ils sont vides, aucun Pod ne matche ou aucun n'est Ready","Redémarrer kube-proxy","Vérifier le certificat TLS de l'Ingress","Augmenter le nombre de réplicas"],
  bonne:0,
  explain:"Endpoints vides → comparer le <code>selector</code> aux labels réels des Pods, puis vérifier la readiness. Ensuite seulement : targetPort vs port écouté, NetworkPolicy, kube-proxy." },

{ id:"c6-02", lvl:6, dom:"Kubernetes",
  q:"Un Pod est OOMKilled alors que la métrique moyenne de mémoire semble basse. Pourquoi ?",
  choix:["L'OOMKill se déclenche sur un PIC instantané, invisible sur une moyenne à 1 minute","La métrique est mal collectée","Le nœud manque de mémoire, pas le Pod","La limite s'applique à tout le namespace"],
  bonne:0,
  explain:"Regarder le MAX de <code>container_memory_working_set_bytes</code>, pas la moyenne. Correctifs : augmenter la limite, régler le heap JVM/Node sur le cgroup, chercher une fuite." },

{ id:"c6-03", lvl:6, dom:"Kubernetes",
  q:"Pendant chaque déploiement, la moitié des requêtes échoue en 502 pendant 30 s. Cause probable ?",
  choix:["Race entre l'arrêt du Pod et la propagation du retrait des endpoints","Le nouveau code est bugué","Le load balancer est saturé","Le certificat TLS est renouvelé"],
  bonne:0,
  explain:"Correctif : hook <code>preStop</code> avec un sleep de 5-10 s, readiness qui bascule en échec avant l'arrêt, <code>terminationGracePeriodSeconds</code> suffisant, arrêt gracieux applicatif." },

{ id:"c6-04", lvl:6, dom:"Kubernetes",
  q:"Un nœud passe NotReady. Au bout de combien de temps ses Pods sont-ils évincés par défaut ?",
  choix:["Environ 5 minutes","Immédiatement","30 secondes","Jamais, il faut intervenir manuellement"],
  bonne:0,
  explain:"Le node controller taint le nœud, les Pods passent Unknown puis sont évincés après le délai de toleration. Exception : un StatefulSet avec volume attaché attend le détachement, pour éviter la double écriture." },

{ id:"c6-05", lvl:6, dom:"Kubernetes",
  q:"Comment déboguer un conteneur distroless (sans shell) en production ?",
  choix:["<code>kubectl debug -it &lt;pod&gt; --image=busybox --target=&lt;conteneur&gt;</code>","<code>kubectl exec -it &lt;pod&gt; -- sh</code>","Reconstruire l'image avec un shell et redéployer","Se connecter en SSH sur le nœud et utiliser docker exec"],
  bonne:0,
  explain:"Le conteneur éphémère partage les namespaces de la cible sans redémarrer le Pod. Variante : <code>--copy-to</code> pour travailler sur une copie, ou <code>kubectl debug node/&lt;node&gt;</code>." },

{ id:"c6-06", lvl:6, dom:"Kubernetes",
  q:"Le DNS interne est intermittent. Quelle piste spécifique à Kubernetes explores-tu ?",
  choix:["<code>ndots:5</code> dans resolv.conf : chaque nom externe génère 4-5 requêtes inutiles, saturant CoreDNS","Le TTL des enregistrements est trop court","Le Service DNS a une mauvaise IP","Les Pods n'ont pas de route par défaut"],
  bonne:0,
  explain:"Autres pistes : réplicas et CPU de CoreDNS, conntrack saturé sur les nœuds, NetworkPolicy bloquant le port 53. Remède courant : NodeLocal DNSCache." },

{ id:"c6-07", lvl:6, dom:"Kubernetes",
  q:"Un namespace reste bloqué en <code>Terminating</code>. Que se passe-t-il ?",
  choix:["Un objet porte un finalizer qu'aucun contrôleur ne lève (opérateur désinstallé, webhook injoignable)","etcd est plein","Le namespace contient trop d'objets","C'est normal, il faut attendre 24 h"],
  bonne:0,
  explain:"On identifie l'objet bloqué dans les conditions du namespace et on répare le contrôleur. Retirer le finalizer à la main est un dernier recours qui peut laisser des ressources cloud orphelines." },

{ id:"c6-08", lvl:6, dom:"Kubernetes",
  q:"Des Pods sont évincés pour <code>ephemeral-storage</code>. Coupable le plus fréquent ?",
  choix:["Des logs applicatifs écrits dans le conteneur au lieu de stdout","Un volume persistant mal dimensionné","Trop d'images sur le nœud uniquement","Un Secret trop volumineux"],
  bonne:0,
  explain:"Correctifs : logger sur stdout, définir <code>ephemeral-storage</code> en requests/limits, garbage collection des images, volume dédié pour les fichiers volumineux." },

{ id:"c6-09", lvl:6, dom:"Kubernetes",
  q:"Après un upgrade de cluster, des manifestes sont refusés. Comment l'anticiper la prochaine fois ?",
  choix:["Scanner les manifestes avec <code>pluto</code>/<code>kubent</code> et surveiller la métrique des API dépréciées","Toujours sauter deux versions mineures d'un coup","Recréer le cluster à chaque montée de version","Désactiver la validation de schéma"],
  bonne:0,
  explain:"Une version d'API a été SUPPRIMÉE (ex. <code>batch/v1beta1</code> → <code>batch/v1</code>). La métrique <code>apiserver_requested_deprecated_apis</code> montre qui utilise encore quoi." },

{ id:"c6-10", lvl:6, dom:"Kubernetes",
  q:"Un HPA oscille entre 2 et 10 réplicas en boucle. Correctif ?",
  choix:["Allonger la <code>stabilizationWindowSeconds</code> et configurer <code>behavior</code> (monter vite, descendre lentement)","Supprimer le HPA","Doubler les limites CPU","Passer en VPA"],
  bonne:0,
  explain:"C'est du flapping. Vérifier aussi que la métrique n'est pas trop bruyante et que la cible n'est pas trop proche de la charge nominale." },

{ id:"c6-11", lvl:6, dom:"Linux",
  q:"Une application répond lentement, CPU normal, réseau bon. Que cherches-tu ?",
  choix:["Les points de sérialisation : pool de connexions saturé, verrou, pauses GC, throttling cgroup","Un problème de DNS","Une fuite mémoire du noyau","Un disque défectueux"],
  bonne:0,
  explain:"Le throttling CPU du cgroup (<code>nr_throttled</code>) est un classique : l'usage MOYEN paraît faible alors que le conteneur est bridé plusieurs fois par seconde." },

{ id:"c6-12", lvl:6, dom:"Linux",
  q:"Comment prouver qu'un problème vient du réseau et non de l'application ?",
  choix:["<code>curl -w</code> décompose DNS/connect/TLS/TTFB, et <code>tcpdump</code> des deux côtés montre si le SYN arrive","En pingant le serveur","En regardant la charge CPU","En comparant les logs applicatifs"],
  bonne:0,
  explain:"Si connect est rapide mais le TTFB lent, c'est l'application. Des retransmissions élevées (<code>ss -ti</code>, <code>netstat -s</code>) désignent le réseau ; leur absence l'innocente." },

{ id:"c6-13", lvl:6, dom:"Linux",
  q:"Le serveur swappe massivement. Que fais-tu ?",
  choix:["Identifier le consommateur et ajuster limites ou taille de machine — le swap est le symptôme, pas la cause","Désactiver le swap immédiatement","Augmenter vm.swappiness","Redémarrer le serveur toutes les nuits"],
  bonne:0,
  explain:"Désactiver le swap transforme une lenteur en OOMKill franc — ce qui est parfois PRÉFÉRABLE (Kubernetes l'exigeait historiquement, pour rendre les limites prévisibles)." },

{ id:"c6-14", lvl:6, dom:"Linux",
  q:"Comment identifier quel processus écrit massivement sur le disque ?",
  choix:["<code>iotop -o</code>, <code>pidstat -d 1</code>, ou <code>/proc/&lt;pid&gt;/io</code>","<code>df -h</code>","<code>du -sh /</code>","<code>free -m</code>"],
  bonne:0,
  explain:"Compléter par <code>lsof -p &lt;pid&gt;</code> pour voir quels fichiers, et <code>iostat -x 1</code> pour identifier le device saturé (%util proche de 100)." },

{ id:"c6-15", lvl:6, dom:"Docker",
  q:"Le disque des nœuds Docker se remplit continuellement. Coupable le plus fréquent ?",
  choix:["Les logs json-file sans rotation dans /var/lib/docker/containers","Les images de base trop lourdes","Le cache de build","Les réseaux orphelins"],
  bonne:0,
  explain:"Correctif : <code>log-opts max-size/max-file</code> dans daemon.json, plus un <code>docker system prune</code> planifié. Diagnostic : <code>docker system df -v</code>." },

{ id:"c6-16", lvl:6, dom:"Docker",
  q:"Le build Docker est lent en CI mais rapide en local. Pourquoi ?",
  choix:["Le runner est éphémère : aucun cache de couches local","Le réseau de la CI est bridé","Docker est plus lent sous Linux","Le Dockerfile est mal ordonné uniquement en CI"],
  bonne:0,
  explain:"Solutions : cache de build distant BuildKit (<code>--cache-from/--cache-to</code> vers le registry), image de base miroir interne, <code>.dockerignore</code> pour réduire le contexte." },

{ id:"c6-17", lvl:6, dom:"Terraform",
  q:"Un <code>apply</code> a échoué à mi-chemin. Que fais-tu ?",
  choix:["Relancer un <code>plan</code> pour voir le delta réel, corriger la cause, ré-appliquer","Restaurer une version antérieure du state","Supprimer le state et tout recréer","Lancer un destroy puis un apply complet"],
  bonne:0,
  explain:"Terraform écrit le state au fur et à mesure : les ressources créées y figurent. Restaurer un ancien state à l'aveugle crée des ressources orphelines." },

{ id:"c6-18", lvl:6, dom:"Terraform",
  q:"Le plan veut détruire/recréer une ressource critique après un simple changement de tag. Que regardes-tu ?",
  choix:["La ligne <code># forces replacement</code> : un attribut immuable a changé","Le fichier de lock","Les permissions du provider","La version de Terraform"],
  bonne:0,
  explain:"Causes fréquentes : nom calculé qui a bougé, défaut modifié par une nouvelle version du provider, clé de <code>for_each</code> changée. Parades : <code>moved</code>, <code>ignore_changes</code>, <code>prevent_destroy</code>." },

{ id:"c6-19", lvl:6, dom:"Terraform",
  q:"Quelqu'un a supprimé une ressource dans la console. Que fait Terraform au prochain plan ?",
  choix:["Il constate son absence et propose de la RECRÉER","Il l'enlève automatiquement du state","Il échoue avec une erreur bloquante","Il ignore la différence"],
  bonne:0,
  explain:"C'est le comportement normal. Si on abandonne sa gestion : <code>state rm</code> + suppression du code. Le vrai correctif est organisationnel : retirer les droits d'écriture manuels." },

{ id:"c6-20", lvl:6, dom:"Terraform",
  q:"Le plan met 20 minutes sur un gros périmètre. Solution DURABLE ?",
  choix:["Découper le state par domaine et par cycle de vie","Utiliser <code>-target</code> systématiquement","Désactiver le refresh en permanence","Augmenter le parallelism à 100"],
  bonne:0,
  explain:"Chaque ressource du state déclenche un appel API au refresh. <code>-target</code> est un outil de dépannage, pas un mode de fonctionnement ; monter le parallelism déclenche du throttling API." },

{ id:"c6-21", lvl:6, dom:"CI/CD",
  q:"Le pipeline passe mais le déploiement casse en production uniquement. Hypothèse n°1 ?",
  choix:["Un écart de CONFIGURATION : variables, secrets, feature flags, endpoints","Un bug du compilateur","Une version de Kubernetes différente","Un problème de licence"],
  bonne:0,
  explain:"Puis : écart de données (volumétrie, migrations), d'infrastructure (proxy, certificats, quotas), d'échelle (concurrence, timeouts). Parade : environnements iso-produits par IaC + smoke tests." },

{ id:"c6-22", lvl:6, dom:"CI/CD",
  q:"Le même pipeline réussit sur une branche et échoue sur une autre. Cause la plus fréquente ?",
  choix:["Les secrets ou variables sont restreints à certaines branches ou environnements protégés","Le runner est différent","Le cache est corrompu","Git est mal configuré"],
  bonne:0,
  explain:"Typiquement, les secrets ne sont pas exposés aux branches non protégées ni aux forks — c'est une protection voulue. On compare les deux exécutions ligne à ligne plutôt que de relancer." },

{ id:"c6-23", lvl:6, dom:"CI/CD",
  q:"Le déploiement a réussi mais l'ancienne version sert encore du trafic. Que vérifies-tu en premier ?",
  choix:["<code>kubectl rollout status</code> : le rollout est-il terminé, ou bloqué sur des Pods non Ready ?","Le DNS","La configuration du WAF","Les logs de la base de données"],
  bonne:0,
  explain:"Autres pistes : cache CDN non invalidé, sticky sessions, ancien ReplicaSet encore à réplicas &gt; 0, ou tag <code>latest</code> avec <code>imagePullPolicy: IfNotPresent</code>." },

{ id:"c6-24", lvl:6, dom:"CI/CD",
  q:"La nouvelle version est en production et la migration de base est déjà passée. Comment revenir en arrière ?",
  choix:["Redéployer l'ancien binaire — possible SI les migrations sont rétrocompatibles ; sinon roll-forward","Restaurer la sauvegarde de la base","Exécuter la migration inverse","Arrêter le service jusqu'à correction"],
  bonne:0,
  explain:"On ne « dé-migre » pas une base en production. La restauration de sauvegarde est un dernier recours assumé, avec perte de données. D'où l'exigence expand/contract." },

{ id:"c6-25", lvl:6, dom:"AWS",
  q:"Une instance EC2 en subnet public ne répond pas en SSH. Que vérifies-tu dans l'ordre ?",
  choix:["IP publique → route vers l'IGW → SG entrant 22 → NACL dans les deux sens → statut de l'instance → sshd","Le mot de passe root","La version de l'AMI","Le quota de vCPU"],
  bonne:0,
  explain:"Un timeout oriente vers SG/NACL/route ; un « connection refused » signifie que le chemin est bon mais que sshd n'écoute pas." },

{ id:"c6-26", lvl:6, dom:"AWS",
  q:"Vos coûts AWS ont doublé. Quels suspects regardes-tu en priorité ?",
  choix:["Transfert de données (inter-AZ, NAT Gateway au Go), volumes et snapshots orphelins, rétention CloudWatch","Le prix des instances a augmenté","Le nombre d'utilisateurs IAM","Le nombre de buckets S3"],
  bonne:0,
  explain:"Cost Explorer groupé par service puis par tag/compte, plus Cost Anomaly Detection pour la date de bascule. Prérequis : un tagging obligatoire imposé par policy." },

{ id:"c6-27", lvl:6, dom:"AWS",
  q:"Une Lambda échoue par intermittence en timeout sur RDS. Cause la plus probable ?",
  choix:["Épuisement des connexions : chaque environnement d'exécution ouvre la sienne","La Lambda manque de mémoire","Le VPC bloque le trafic","La base est en maintenance"],
  bonne:0,
  explain:"Solutions : RDS Proxy pour mutualiser, réutiliser la connexion hors du handler, plafonner la concurrence réservée, timeouts courts côté client." },

{ id:"c6-28", lvl:6, dom:"Azure",
  q:"Une App Service ne joint pas une base derrière un Private Endpoint. Que vérifies-tu ?",
  choix:["VNet Integration activée + Private DNS Zone liée au VNet + <code>vnetRouteAllEnabled</code>","Le pare-feu Windows de l'App Service","Le certificat TLS de la base","Le nombre d'instances du plan"],
  bonne:0,
  explain:"Sans intégration VNet ou sans zone DNS privée, le FQDN résout encore vers l'IP publique. Vérifier aussi NSG/UDR sur le subnet d'intégration." },

{ id:"c6-29", lvl:6, dom:"Azure",
  q:"Un déploiement ARM/Bicep échoue en <code>Conflict</code>. Que comprends-tu du plan de contrôle Azure ?",
  choix:["ARM est asynchrone et sérialise les opérations sur une même ressource : il faut retry avec backoff","La ressource est verrouillée définitivement","Le template est invalide","Le quota est atteint"],
  bonne:0,
  explain:"Éviter les apply concurrents sur un même RG, tenir compte de la cohérence à terme et des Resource Locks. Un Terraform très parallèle déclenche aussi du throttling (429 + Retry-After)." },

{ id:"c6-30", lvl:6, dom:"Sécurité",
  q:"Une clé d'accès AWS a fuité sur GitHub. Quelle est la PREMIÈRE action ?",
  choix:["Désactiver puis supprimer la clé immédiatement","Nettoyer l'historique Git","Rendre le dépôt privé","Ouvrir un ticket au support AWS"],
  bonne:0,
  explain:"Ensuite : CloudTrail pour inventorier l'usage, chercher la persistance (nouveaux users/rôles/clés), nettoyer l'historique, puis post-mortem sur l'existence même d'une clé statique." },

{ id:"c6-31", lvl:6, dom:"Sécurité",
  q:"Un scan remonte 200 CVE sur une image. Comment priorises-tu ?",
  choix:["Par risque réel : sévérité ET exploitabilité, exposition du service, présence dans le chemin d'exécution","Par ordre décroissant de score CVSS uniquement","Par ordre alphabétique des paquets","Toutes en même temps, sinon ça n'a pas de sens"],
  bonne:0,
  explain:"Beaucoup de CVE viennent de l'image de base : passer à une base minimale (distroless, slim) en élimine souvent la majorité d'un seul coup." },

{ id:"c6-32", lvl:6, dom:"Sécurité",
  q:"Tu découvres un conteneur en production avec le socket Docker monté. Quel est le risque ?",
  choix:["Contrôle du daemon : on peut lancer un conteneur privilégié qui monte / — c'est root sur le nœud","Un simple risque de fuite de logs","Une consommation excessive de CPU","Aucun si le conteneur tourne en non-root"],
  bonne:0,
  explain:"Remèdes : retirer le montage, utiliser un builder sans daemon (Kaniko, Buildah), et une politique d'admission qui interdit hostPath sur le socket et les conteneurs privilégiés." },

{ id:"c6-33", lvl:6, dom:"Observabilité",
  q:"Prometheus consomme 40 Go de RAM et redémarre. Cause quasi certaine ?",
  choix:["Explosion de cardinalité : un label à valeurs illimitées a créé des millions de séries","La rétention est trop longue","Trop de dashboards Grafana","Le disque est trop lent"],
  bonne:0,
  explain:"Diagnostic : <code>topk</code> sur <code>count by (__name__)</code>, page TSDB status. Correctifs : relabeling au scrape, long terme déporté (Thanos, Mimir), recording rules." },

{ id:"c6-34", lvl:6, dom:"Observabilité",
  q:"Les traces s'arrêtent au deuxième service. Pourquoi ?",
  choix:["Le contexte de trace n'est pas propagé : service non instrumenté, en-têtes filtrés, ou formats incompatibles","L'échantillonnage est trop agressif","Le backend de tracing est saturé","Les horloges ne sont pas synchronisées"],
  bonne:0,
  explain:"La propagation se fait par l'en-tête W3C <code>traceparent</code>. Attention aussi aux passages par une file de messages sans injection du contexte dans les en-têtes du message." },

{ id:"c6-35", lvl:6, dom:"SRE",
  q:"Une panne est en cours et personne ne sait qui décide. Que mets-tu en place ?",
  choix:["Des rôles explicites : Incident Commander qui décide sans taper au clavier, Operations, Communications, Scribe","Un canal Slack par équipe technique","Un rapport détaillé avant toute action","Une réunion de crise avec tous les managers"],
  bonne:0,
  explain:"Un canal unique, des points de situation réguliers, la priorité à la MITIGATION avant la compréhension, et un post-mortem blameless sous 48 h avec actions datées." },

{ id:"c6-36", lvl:6, dom:"SQL",
  q:"Une requête passe de 50 ms à 30 s sans changement de code. Que s'est-il passé ?",
  choix:["Le plan d'exécution a changé : statistiques périmées, volume, index supprimé, ou bind parameter sniffing","Le réseau est saturé","La base a été redémarrée","Le cache applicatif est vide"],
  bonne:0,
  explain:"Comparer <code>EXPLAIN ANALYZE</code> avec l'ancien plan, relancer <code>ANALYZE</code>, vérifier la croissance de la table et la sélectivité des index." },

{ id:"c6-37", lvl:6, dom:"Réseau",
  q:"Un appel HTTPS échoue côté serveur applicatif mais fonctionne dans le navigateur. Cause probable ?",
  choix:["Chaîne de certificats incomplète, ou CA d'entreprise absente du truststore du conteneur","Le serveur bloque les user-agents non navigateurs","Le protocole HTTP/2 n'est pas supporté","Le cookie de session manque"],
  bonne:0,
  explain:"Un navigateur peut compléter une chaîne incomplète, pas un client Java/Go/curl. Vérification : <code>openssl s_client -connect host:443 -showcerts</code>." }

]);
