window.QCM = (window.QCM || []).concat([
/* ============ QCM NIVEAU 1 — VOCABULAIRE & FONDATIONS ============
   Propositions calibrées : longueurs comparables, distracteurs plausibles.  */

{ id:"c1-01", lvl:1, dom:"Linux",
  q:"Dans <code>drwxr-xr-x</code>, que représente le tout premier caractère ?",
  choix:["Le type de l'objet : répertoire, fichier, lien","Le droit de lecture accordé au propriétaire","Le droit d'exécution accordé à tous","Le fait que l'objet soit un fichier caché"],
  bonne:0,
  explain:"C'est le TYPE, pas une permission : <code>d</code> répertoire, <code>-</code> fichier ordinaire, <code>l</code> lien symbolique, <code>b</code>/<code>c</code> périphérique, <code>s</code> socket. Les permissions ne commencent qu'au 2ᵉ caractère." },

{ id:"c1-02", lvl:1, dom:"Linux",
  q:"<code>chmod 640 fichier</code> donne quels droits ?",
  choix:["Propriétaire rw · groupe r · autres rien","Propriétaire rwx · groupe rw · autres r","Propriétaire r · groupe rien · autres rien","Propriétaire rw · groupe rw · autres rw"],
  bonne:0,
  explain:"6 = rw- (4+2), 4 = r--, 0 = ---. Chaque chiffre est une somme : lecture 4, écriture 2, exécution 1." },

{ id:"c1-03", lvl:1, dom:"Linux",
  q:"Quelle est la différence entre <code>&gt;</code> et <code>&gt;&gt;</code> ?",
  choix:["<code>&gt;</code> écrase le fichier, <code>&gt;&gt;</code> ajoute à la fin","<code>&gt;</code> ajoute à la fin, <code>&gt;&gt;</code> écrase le fichier","<code>&gt;</code> écrit stdout, <code>&gt;&gt;</code> écrit stderr","<code>&gt;</code> crée le fichier, <code>&gt;&gt;</code> exige qu'il existe"],
  bonne:0,
  explain:"<code>&gt;</code> tronque le fichier avant d'écrire — et il le fait MÊME si la commande échoue ensuite. C'est le piège classique qui vide un fichier de configuration." },

{ id:"c1-04", lvl:1, dom:"Linux",
  q:"Que fait <code>2&gt;&amp;1</code> ?",
  choix:["Il envoie stderr là où pointe stdout","Il envoie stdout là où pointe stderr","Il fusionne le contenu de deux fichiers","Il exécute la commande une seconde fois"],
  bonne:0,
  explain:"Le descripteur 2 est redirigé vers la destination du descripteur 1 À CET INSTANT. D'où l'importance de l'ordre : <code>cmd &gt; f 2&gt;&amp;1</code> marche, <code>cmd 2&gt;&amp;1 &gt; f</code> laisse stderr sur le terminal." },

{ id:"c1-05", lvl:1, dom:"Linux",
  q:"À quoi sert <code>export</code> devant une variable ?",
  choix:["À la transmettre aux processus enfants","À la rendre permanente après un redémarrage","À la protéger contre toute modification","À la partager avec les autres utilisateurs"],
  bonne:0,
  explain:"<code>export</code> promeut une variable de shell en variable d'ENVIRONNEMENT, héritée par les enfants. C'est ce mécanisme qui transporte la configuration dans les conteneurs." },

{ id:"c1-06", lvl:1, dom:"Docker",
  q:"Quel énoncé décrit correctement image et conteneur ?",
  choix:["L'image est un modèle figé, le conteneur une instance qui tourne","Le conteneur est le modèle figé, l'image l'instance qui tourne","L'image contient les données, le conteneur contient le code","Ce sont deux appellations du même objet technique"],
  bonne:0,
  explain:"Analogie classe / objet : l'image est un empilement de couches en lecture seule ; le conteneur ajoute par-dessus une couche d'écriture éphémère." },

{ id:"c1-07", lvl:1, dom:"Docker",
  q:"Pourquoi un conteneur n'est-il pas une machine virtuelle ?",
  choix:["Il partage le noyau de l'hôte, c'est un processus isolé","Il utilise un hyperviseur plus léger et optimisé","Il embarque un OS minimaliste au lieu d'un OS complet","Il ne peut pas accéder directement au réseau physique"],
  bonne:0,
  explain:"Namespaces + cgroups + rootfs overlay, rien de plus. D'où un démarrage en millisecondes, mais une isolation plus faible et une dépendance au noyau de l'hôte." },

{ id:"c1-08", lvl:1, dom:"Docker",
  q:"Que deviennent les données écrites dans un conteneur supprimé ?",
  choix:["Elles sont perdues, sauf si un volume est monté","Elles sont conservées dans l'image d'origine","Elles sont recopiées automatiquement sur l'hôte","Elles sont sauvegardées par le daemon Docker"],
  bonne:0,
  explain:"La couche d'écriture est liée au cycle de vie du conteneur. Pour persister : volume nommé, bind mount, ou stockage externe. Un conteneur doit être stateless par défaut." },

{ id:"c1-09", lvl:1, dom:"Kubernetes",
  q:"Qu'est-ce qu'un Pod ?",
  choix:["Un ou plusieurs conteneurs partageant IP et volumes","Un conteneur unique, sous un autre nom","Un groupe de nœuds gérés ensemble","Un cloisonnement logique du cluster"],
  bonne:0,
  explain:"C'est la plus petite unité déployable. Les conteneurs d'un Pod partagent le namespace réseau (même IP, communication via localhost) et les volumes — d'où le pattern sidecar." },

{ id:"c1-10", lvl:1, dom:"Kubernetes",
  q:"Quel problème un Service Kubernetes résout-il ?",
  choix:["Les Pods changent d'IP : il donne une adresse stable","Les Pods manquent de mémoire : il ajuste les limites","Les Pods sont mal répartis : il choisit les nœuds","Les Pods perdent leurs données : il monte les volumes"],
  bonne:0,
  explain:"IP virtuelle et nom DNS stables, avec répartition du trafic sur les Pods correspondant à son <code>selector</code>. Sans lui, il faudrait suivre des IP qui changent à chaque recréation." },

{ id:"c1-11", lvl:1, dom:"Kubernetes",
  q:"Que se passe-t-il si tu supprimes à la main un Pod d'un Deployment ?",
  choix:["Le ReplicaSet en recrée aussitôt un nouveau","Il disparaît définitivement du cluster","Le Deployment bascule en état d'erreur","Le nœud concerné passe en NotReady"],
  bonne:0,
  explain:"C'est la boucle de réconciliation : le contrôleur compare l'état désiré (N réplicas) à l'état observé et corrige. Pour arrêter le service, il faut modifier le Deployment." },

{ id:"c1-12", lvl:1, dom:"Terraform",
  q:"Que signifie « Terraform est déclaratif » ?",
  choix:["Tu décris l'état final, il calcule les actions","Tu écris les commandes à exécuter, dans l'ordre","Le code s'exécute ligne par ligne, comme un script","Tu déclares les variables avant les ressources"],
  bonne:0,
  explain:"Conséquence pratique : c'est idempotent. Relancer un <code>apply</code> sans changement ne fait rien, là où un script bash rejoue tout." },

{ id:"c1-13", lvl:1, dom:"Terraform",
  q:"À quoi sert le fichier <code>terraform.tfstate</code> ?",
  choix:["À mémoriser le lien entre le code et le réel","À conserver l'historique des commandes lancées","À stocker les identifiants d'accès au cloud","À lister les providers restant à télécharger"],
  bonne:0,
  explain:"Sans lui, Terraform ne sait plus ce qu'il gère et voudrait tout recréer. Il contient souvent des secrets en clair : backend distant chiffré obligatoire, jamais dans Git." },

{ id:"c1-14", lvl:1, dom:"Terraform",
  q:"Différence entre un bloc <code>resource</code> et un bloc <code>data</code> ?",
  choix:["<code>resource</code> gère l'objet, <code>data</code> le lit seulement","<code>data</code> crée l'objet, <code>resource</code> le lit seulement","<code>data</code> ne concerne que les bases de données","Aucune : ce sont deux syntaxes équivalentes"],
  bonne:0,
  explain:"Une data source est en lecture seule : un <code>destroy</code> ne supprimera jamais ce qu'elle référence. On l'utilise pour récupérer l'ID d'un objet créé ailleurs." },

{ id:"c1-15", lvl:1, dom:"Terraform",
  q:"Que fait <code>terraform init</code> ?",
  choix:["Il installe providers et modules, et règle le backend","Il crée réellement les ressources dans le cloud","Il affiche les changements qui seraient appliqués","Il reformate les fichiers .tf au format canonique"],
  bonne:0,
  explain:"Obligatoire au premier usage et après tout changement de provider, de backend ou de module. Il ne touche jamais à l'infrastructure." },

{ id:"c1-16", lvl:1, dom:"AWS",
  q:"Quelle est la relation entre une Région et une Availability Zone ?",
  choix:["Une Région contient plusieurs AZ isolées","Une AZ contient plusieurs Régions voisines","Une AZ est partagée entre plusieurs Régions","Ce sont deux appellations du même concept"],
  bonne:0,
  explain:"eu-west-3 (Paris) contient plusieurs AZ reliées à faible latence. La haute disponibilité se construit multi-AZ ; la reprise après sinistre se construit multi-région." },

{ id:"c1-17", lvl:1, dom:"AWS",
  q:"Un bucket S3 est rendu public par erreur. Qui est responsable ?",
  choix:["Le client : il gère la sécurité DANS le cloud","AWS : il gère la sécurité de ses propres services","L'auditeur : il aurait dû détecter la configuration","Personne : c'est un comportement attendu du service"],
  bonne:0,
  explain:"AWS sécurise LE cloud (matériel, hyperviseur, réseau physique). Le client sécurise DANS le cloud : IAM, chiffrement, configuration, patchs de l'OS, données." },

{ id:"c1-18", lvl:1, dom:"Azure",
  q:"Que se passe-t-il si tu supprimes un Resource Group Azure ?",
  choix:["Toutes les ressources qu'il contient sont supprimées","Les ressources migrent vers un groupe par défaut","Seul le groupe disparaît, les ressources subsistent","La suppression échoue tant qu'il n'est pas vide"],
  bonne:0,
  explain:"Le RG regroupe des ressources partageant un cycle de vie, et toute ressource appartient à exactement un RG. C'est puissant… et dangereux sans Resource Lock." },

{ id:"c1-19", lvl:1, dom:"Azure",
  q:"Quelle est la hiérarchie Azure, du plus large au plus fin ?",
  choix:["Management Group, Subscription, Resource Group, Ressource","Subscription, Management Group, Resource Group, Ressource","Tenant, Resource Group, Subscription, Ressource","Resource Group, Management Group, Subscription, Ressource"],
  bonne:0,
  explain:"Policies et RBAC s'héritent du haut vers le bas : une assignation au niveau management group couvre toutes les subscriptions en dessous, présentes et futures." },

{ id:"c1-20", lvl:1, dom:"Réseau",
  q:"Combien d'adresses contient un réseau en <code>/24</code> ?",
  choix:["256","24","512","1024"],
  bonne:0,
  explain:"2^(32−24) = 2^8 = 256. Sur AWS, 5 sont réservées par la plateforme : il reste 251 adresses utilisables." },

{ id:"c1-21", lvl:1, dom:"Réseau",
  q:"Dans quel cas choisit-on UDP plutôt que TCP ?",
  choix:["Quand la latence prime sur la fiabilité","Quand l'ordre des paquets doit être garanti","Quand on transfère un fichier volumineux","Quand on veut un handshake chiffré"],
  bonne:0,
  explain:"TCP apporte handshake, retransmission, ordre garanti et contrôle de flux, au prix de la latence. UDP n'offre aucune garantie mais aucun surcoût : DNS, VoIP, streaming, métriques." },

{ id:"c1-22", lvl:1, dom:"Réseau",
  q:"Pourquoi un CNAME est-il interdit à la racine d'un domaine ?",
  choix:["La racine doit porter ses enregistrements SOA et NS","Les CNAME sont réservés aux sous-domaines par usage","C'est autorisé, mais mauvais pour la performance","Les registrars le facturent comme une option"],
  bonne:0,
  explain:"Un CNAME interdit tout autre enregistrement sur le même nom. D'où les enregistrements ALIAS/ANAME propriétaires : Route 53 Alias, Azure DNS Alias." },

{ id:"c1-23", lvl:1, dom:"Git",
  q:"Quelle est la différence entre <code>git fetch</code> et <code>git pull</code> ?",
  choix:["<code>pull</code> intègre en plus, <code>fetch</code> se contente de rapatrier","<code>fetch</code> intègre en plus, <code>pull</code> se contente de rapatrier","<code>fetch</code> envoie tes commits vers le serveur distant","Aucune : <code>pull</code> est un alias de <code>fetch</code>"],
  bonne:0,
  explain:"<code>pull</code> = <code>fetch</code> + <code>merge</code> (ou rebase) : il modifie ta branche. Avec <code>fetch</code>, on regarde avant de décider." },

{ id:"c1-24", lvl:1, dom:"Git",
  q:"Qu'est-ce qu'une branche Git, techniquement ?",
  choix:["Un pointeur mobile vers un commit","Une copie complète du répertoire de travail","Un répertoire dédié à l'intérieur de .git","Un fichier de différences par rapport à main"],
  bonne:0,
  explain:"41 octets dans <code>.git/refs/heads/</code>. C'est pour ça que créer une branche est instantané et gratuit." },

{ id:"c1-25", lvl:1, dom:"Git",
  q:"Un fichier ajouté au <code>.gitignore</code> apparaît toujours dans tes commits. Pourquoi ?",
  choix:["Il est déjà suivi : il faut <code>git rm --cached</code>","Le .gitignore doit être placé à la racine du disque","Il faut relancer <code>git init</code> pour le recharger","Le .gitignore ne s'applique qu'aux répertoires"],
  bonne:0,
  explain:"<code>.gitignore</code> n'empêche que le suivi de NOUVEAUX fichiers. C'est la raison numéro un pour laquelle un <code>.env</code> reste commité." },

{ id:"c1-26", lvl:1, dom:"CI/CD",
  q:"Différence entre Continuous Delivery et Continuous Deployment ?",
  choix:["En Delivery, un humain déclenche la mise en production","En Deployment, un humain déclenche la mise en production","En Delivery, on ne déploie jamais en production","En Deployment, on se passe complètement de tests"],
  bonne:0,
  explain:"Delivery : chaque build est PRÊT à partir. Deployment : tout build qui passe les tests part effectivement. En banque, on est presque toujours en Delivery." },

{ id:"c1-27", lvl:1, dom:"CI/CD",
  q:"Pourquoi construire un artefact UNE seule fois pour tous les environnements ?",
  choix:["Pour déployer exactement ce qui a été testé","Pour économiser du temps de calcul en CI","Pour respecter les quotas des registries","Pour éviter les collisions de numéros de version"],
  bonne:0,
  explain:"Principe <em>build once, deploy many</em> : on construit un artefact versionné puis on le PROMEUT dev → recette → prod. Seule la configuration change." },

{ id:"c1-28", lvl:1, dom:"Sécurité",
  q:"Quelle est la différence entre authentification et autorisation ?",
  choix:["L'une prouve qui tu es, l'autre ce que tu peux faire","L'une vaut pour les humains, l'autre pour les machines","L'autorisation s'effectue toujours en premier","Ce sont deux traductions du même terme anglais"],
  bonne:0,
  explain:"AuthN puis AuthZ, toujours dans cet ordre. Un token valide (authentifié) ne donne pas forcément le droit d'agir (autorisé)." },

{ id:"c1-29", lvl:1, dom:"Sécurité",
  q:"Que fait-on d'un mot de passe utilisateur avant de le stocker ?",
  choix:["On le hache, salé, avec bcrypt ou argon2","On le chiffre en AES avec une clé serveur","On l'encode en base64 puis on le stocke","On le stocke en clair dans une table protégée"],
  bonne:0,
  explain:"Le hachage est à SENS UNIQUE : on compare des empreintes. Chiffrer serait réversible — qui a la clé a tous les mots de passe. Le base64 n'est pas du chiffrement du tout." },

{ id:"c1-30", lvl:1, dom:"Observabilité",
  q:"Quels sont les trois piliers de l'observabilité ?",
  choix:["Métriques, logs, traces","Alertes, dashboards, rapports","Processeur, mémoire, disque","Prévention, détection, réaction"],
  bonne:0,
  explain:"Métriques (QUOI : agrégats, alerting), logs (POURQUOI : événements détaillés), traces (OÙ : parcours d'une requête). Les trois se corrèlent par un trace ID." },

{ id:"c1-31", lvl:1, dom:"SRE",
  q:"Lequel de ces engagements comporte des pénalités contractuelles ?",
  choix:["Le SLA","Le SLO","Le SLI","Les trois"],
  bonne:0,
  explain:"SLI = l'indicateur mesuré. SLO = l'objectif interne. SLA = l'engagement contractuel. Règle : SLA &lt; SLO, pour garder une marge avant de payer." },

{ id:"c1-32", lvl:1, dom:"SRE",
  q:"Avec un SLO de 99,9 %, quel budget d'indisponibilité mensuel ?",
  choix:["Environ 43 minutes","Environ 4 minutes","Environ 7 heures","Environ 3 jours"],
  bonne:0,
  explain:"0,1 % de 30 jours ≈ 43 min. C'est l'<em>error budget</em> : tant qu'il en reste on déploie vite ; consommé, on gèle les features pour la fiabilité." },

{ id:"c1-33", lvl:1, dom:"SQL",
  q:"Que garantit le « A » d'ACID ?",
  choix:["Atomicité : tout la transaction, ou rien du tout","Accessibilité : les données restent toujours lisibles","Authentification : l'utilisateur est vérifié","Archivage : les données sont conservées"],
  bonne:0,
  explain:"Atomicité (tout ou rien), Cohérence (contraintes respectées), Isolation (les transactions concurrentes ne se voient pas à moitié), Durabilité (survit à un crash)." },

{ id:"c1-34", lvl:1, dom:"SQL",
  q:"Quelle jointure garde toutes les lignes de la table de gauche ?",
  choix:["LEFT JOIN","INNER JOIN","CROSS JOIN","Aucune des trois"],
  bonne:0,
  explain:"Le LEFT JOIN remplit de NULL les colonnes de droite quand rien ne correspond — d'où son usage pour trouver les orphelins avec <code>WHERE b.id IS NULL</code>." },

{ id:"c1-35", lvl:1, dom:"SQL",
  q:"Quelle commande supprime la table elle-même, structure comprise ?",
  choix:["DROP","DELETE","TRUNCATE","PURGE"],
  bonne:0,
  explain:"<code>DELETE</code> supprime des lignes (avec WHERE, annulable). <code>TRUNCATE</code> vide toute la table très vite. <code>DROP</code> supprime la table." }

]);
