window.QCM = (window.QCM || []).concat([
/* ============ QCM NIVEAU 7 — ARCHITECTURE & PRODUCTION ============ */

{ id:"c7-01", lvl:7, dom:"SRE",
  q:"On te demande une application « hautement disponible ». Que fais-tu en premier ?",
  choix:["Tu poses des questions : SLO réel, RTO/RPO, budget, état ou pas, contraintes réglementaires","Tu proposes une architecture multi-région actif/actif","Tu doubles le nombre de réplicas","Tu ajoutes un load balancer"],
  bonne:0,
  explain:"Répondre « multi-région » sans ces réponses est le piège classique : c'est cher, complexe, et souvent inutile. La question teste la capacité à cadrer avant de concevoir." },

{ id:"c7-02", lvl:7, dom:"Kubernetes",
  q:"Tu as 3 nœuds et 3 réplicas. Es-tu protégé contre la perte d'un nœud ?",
  choix:["Pas automatiquement : le scheduler peut placer les 3 Pods sur le même nœud","Oui, Kubernetes répartit toujours les réplicas","Oui, si le Deployment a une readiness probe","Oui, à condition d'avoir un Service"],
  bonne:0,
  explain:"Il faut l'expliciter avec <code>topologySpreadConstraints</code> (hostname, puis zone) ou une podAntiAffinity — et prévoir la capacité pour que N-1 nœuds absorbent la charge." },

{ id:"c7-03", lvl:7, dom:"Kubernetes",
  q:"Faut-il faire tourner une base de données de production en Kubernetes ?",
  choix:["Par défaut non en banque : un service managé fournit sauvegardes, PITR, patchs et HA sans coût opérationnel","Oui, toujours : c'est plus portable","Non, c'est techniquement impossible","Oui, si on utilise un StatefulSet"],
  bonne:0,
  explain:"On peut le faire avec un opérateur mature (CloudNativePG, Vitess) et une vraie compétence interne. Le point évalué : savoir arbitrer coût opérationnel vs contrôle." },

{ id:"c7-04", lvl:7, dom:"Kubernetes",
  q:"Comment isoler plusieurs équipes sur un cluster mutualisé ?",
  choix:["Namespace + RBAC + ResourceQuota + NetworkPolicy default-deny + Pod Security + policies d'admission","Un namespace par équipe suffit","Un nœud dédié par équipe","Des Services de type ClusterIP uniquement"],
  bonne:0,
  explain:"Limite honnête à énoncer : l'isolation reste souple. Pour un vrai cloisonnement réglementaire, on sépare les CLUSTERS — c'est ce qui se fait entre prod et hors-prod en banque." },

{ id:"c7-05", lvl:7, dom:"Kubernetes",
  q:"Quel est le coût réel d'un service mesh ?",
  choix:["Un sidecar par Pod (CPU, mémoire, quelques ms de latence) et une couche de plus à opérer","Une licence par nœud","L'impossibilité d'utiliser des NetworkPolicy","La perte du rolling update"],
  bonne:0,
  explain:"Apports : mTLS automatique, routage fin, retries et circuit breakers hors du code, métriques uniformes. À justifier par un besoin, pas par la mode." },

{ id:"c7-06", lvl:7, dom:"Terraform",
  q:"Sur quel critère découpes-tu tes states Terraform ?",
  choix:["Par rayon d'impact et par cycle de vie : socle réseau / plateforme / applications","Un state par ressource","Un seul state par cloud provider","Par ordre alphabétique des ressources"],
  bonne:0,
  explain:"Bénéfices : plan rapide, erreur circonscrite, droits séparés, verrous indépendants. Coût : des contrats explicites entre states." },

{ id:"c7-07", lvl:7, dom:"Terraform",
  q:"Dans un pipeline Terraform, qu'applique-t-on après l'approbation ?",
  choix:["Le plan SAUVEGARDÉ qui a été revu, pas un nouveau plan recalculé","Un nouveau plan, pour être à jour","Directement les fichiers .tf","Le plan de l'environnement précédent"],
  bonne:0,
  explain:"Appliquer le plan revu garantit que ce qui est exécuté est exactement ce qui a été approuvé. Un replan pourrait avoir changé entre-temps." },

{ id:"c7-08", lvl:7, dom:"AWS",
  q:"Quelle stratégie multi-compte recommandes-tu pour une grande organisation ?",
  choix:["AWS Organizations, OU par usage, un compte par application ET par environnement, comptes centraux Log Archive et Security","Un compte unique avec des tags rigoureux","Un compte par développeur","Deux comptes : prod et non-prod"],
  bonne:0,
  explain:"Bénéfices : isolation dure du rayon d'impact et des quotas, facturation par équipe, SCP différenciées par OU. Control Tower / LZA pour industrialiser." },

{ id:"c7-09", lvl:7, dom:"AWS",
  q:"Quel levier d'optimisation de coûts appliquer AVANT de prendre des Savings Plans ?",
  choix:["Le rightsizing et le nettoyage : on ne s'engage pas 3 ans sur du gaspillage","La migration vers Graviton","L'achat d'instances réservées","Le passage en multi-région"],
  bonne:0,
  explain:"Ordre : visibilité (tags) → rightsizing → extinction du hors-prod → engagements sur la base stable → Spot → stockage et transfert de données." },

{ id:"c7-10", lvl:7, dom:"AWS",
  q:"Où placer une NAT Gateway pour un VPC hautement disponible ?",
  choix:["Une par AZ, dans les subnets publics","Une seule, dans un subnet privé","Une seule, dans un subnet public","Aucune, l'IGW suffit"],
  bonne:0,
  explain:"Le NAT a besoin d'une EIP et d'une route vers l'IGW, donc d'un subnet public. Une seule NAT = point de défaillance unique ET trafic inter-AZ facturé." },

{ id:"c7-11", lvl:7, dom:"Azure",
  q:"Que contient une landing zone Azure ?",
  choix:["Hiérarchie de management groups, subscriptions par usage, policies, RBAC/PIM, réseau hub-and-spoke, journalisation centralisée","Uniquement les VNets et les NSG","Les applications métier","Un abonnement de test"],
  bonne:0,
  explain:"C'est le socle de gouvernance déployé AVANT les applications, entièrement en IaC (CAF/ALZ Terraform ou Bicep). Vocabulaire attendu chez un grand compte." },

{ id:"c7-12", lvl:7, dom:"Azure",
  q:"AKS, App Service ou Container Apps : quel est le critère décisif ?",
  choix:["La maturité et la taille de l'équipe qui devra l'exploiter","La popularité de la technologie","Le prix affiché par mois","La compatibilité avec Terraform"],
  bonne:0,
  explain:"App Service = défaut raisonnable pour une app web. Container Apps = microservices sans gérer de cluster. AKS = besoin de contrôle fin ET équipe capable d'opérer un cluster à 3 h du matin." },

{ id:"c7-13", lvl:7, dom:"Azure",
  q:"Comment garantir la conformité de 200 abonnements ?",
  choix:["Des initiatives Azure Policy assignées au niveau management group, avec remédiation et exemptions datées","Un audit manuel trimestriel","Un script PowerShell planifié","Des alertes Azure Monitor"],
  bonne:0,
  explain:"L'assignation au management group couvre les abonnements présents ET futurs. Les exceptions passent par une exemption tracée, jamais par une désactivation." },

{ id:"c7-14", lvl:7, dom:"CI/CD",
  q:"Comment éviter de dupliquer 50 fois le même YAML de pipeline ?",
  choix:["Des templates/workflows réutilisables versionnés dans un dépôt central, paramétrés par service","Un script qui copie le YAML dans chaque dépôt","Un monorepo unique","Des variables d'environnement globales"],
  bonne:0,
  explain:"Point d'attention : VERSIONNER les templates par tag immuable. Les consommer sur <code>@main</code>, c'est casser 50 équipes le jour où on modifie le template." },

{ id:"c7-15", lvl:7, dom:"CI/CD",
  q:"Quelles sont les quatre métriques DORA ?",
  choix:["Fréquence de déploiement, lead time, taux d'échec des changements, temps de rétablissement","Couverture de tests, dette technique, vélocité, bugs ouverts","Uptime, latence, throughput, erreurs","Nombre de commits, de PR, de builds, de déploiements"],
  bonne:0,
  explain:"Les deux premières mesurent la VITESSE, les deux dernières la STABILITÉ. Résultat clé : elles progressent ENSEMBLE — déployer souvent en petits lots réduit le risque." },

{ id:"c7-16", lvl:7, dom:"CI/CD",
  q:"Comment gérer une release nécessitant 5 services interdépendants ?",
  choix:["Rétrocompatibilité des contrats d'API + tests de contrat + déploiement indépendant + feature flags","Une fenêtre de déploiement coordonnée un dimanche","Un script qui déploie les 5 dans le bon ordre","Fusionner les 5 services en un seul"],
  bonne:0,
  explain:"Si une coordination stricte reste nécessaire, c'est un signal de couplage à corriger dans l'architecture, pas un problème de planification." },

{ id:"c7-17", lvl:7, dom:"Sécurité",
  q:"Que signifie le zero trust appliqué au cloud ?",
  choix:["Chaque appel est authentifié et autorisé, quelle que soit sa provenance — plus de réseau interne de confiance","Interdire tout accès depuis internet","Chiffrer tous les disques","Supprimer les comptes administrateurs"],
  bonne:0,
  explain:"En pratique : identité forte partout (mTLS, identités de charge), autorisation contextuelle, micro-segmentation, chiffrement, journalisation exhaustive. Le périmètre reste utile en défense en profondeur." },

{ id:"c7-18", lvl:7, dom:"Sécurité",
  q:"Comment sécuriser la chaîne CI/CD elle-même ?",
  choix:["Branches protégées, runners éphémères isolés, OIDC sans secret long, actions tierces épinglées par digest, séparation build/deploy","Un antivirus sur les runners","Un VPN pour accéder au forge","Des mots de passe complexes"],
  bonne:0,
  explain:"Qui contrôle le pipeline contrôle la production : c'est la cible privilégiée. Attention aux déclencheurs qui exécutent du code de fork avec les secrets du dépôt." },

{ id:"c7-19", lvl:7, dom:"Observabilité",
  q:"Qu'est-ce qui casse une trace distribuée de bout en bout ?",
  choix:["Un service qui ne propage pas le contexte (en-tête traceparent)","Un backend de tracing trop lent","Un échantillonnage à 100 %","Des horloges désynchronisées"],
  bonne:0,
  explain:"OpenTelemetry standardise l'instrumentation et la propagation. Sans elle, la trace se coupe au premier service non instrumenté — y compris au passage par une file de messages." },

{ id:"c7-20", lvl:7, dom:"Observabilité",
  q:"Quels critères doit remplir une alerte qui réveille à 3 h du matin ?",
  choix:["Impact utilisateur réel + urgence + action possible avec un runbook","Un seuil technique dépassé","Une anomalie détectée par l'IA","La demande d'un manager"],
  bonne:0,
  explain:"Tout le reste va en ticket ou en dashboard. On alerte sur le burn rate du budget d'erreur (multi-fenêtres) plutôt que sur un seuil instantané, et on mesure les faux positifs." },

{ id:"c7-21", lvl:7, dom:"SRE",
  q:"Comment introduire le chaos engineering en banque ?",
  choix:["Progressivement : d'abord en recette, périmètre défini, hypothèse écrite, bouton d'arrêt, fenêtre annoncée","Directement en production, sinon ça n'a pas de valeur","En simulant les pannes sur un tableau blanc","En laissant l'outil injecter des pannes au hasard"],
  bonne:0,
  explain:"Le principe : injecter une panne pour VALIDER une hypothèse de résilience. On ne passe en production qu'après avoir démontré la valeur et obtenu l'adhésion du risque opérationnel." },

{ id:"c7-22", lvl:7, dom:"SRE",
  q:"Comment dimensionner pour un pic connu (clôture mensuelle) ?",
  choix:["Test de charge pour trouver le point de rupture, identifier le vrai goulot, puis PRÉ-scaler avant le pic","Se reposer sur l'autoscaling","Doubler toutes les ressources en permanence","Limiter le nombre d'utilisateurs simultanés"],
  bonne:0,
  explain:"L'autoscaling réactif arrive trop tard face à un pic brutal. Et le facteur limitant est souvent la base ou un pool de connexions, pas le CPU applicatif." },

{ id:"c7-23", lvl:7, dom:"SRE",
  q:"Monolithe ou microservices pour une nouvelle application ?",
  choix:["Commencer par un monolithe modulaire, extraire un service quand un besoin réel apparaît","Microservices dès le départ, c'est l'état de l'art","Monolithe, toujours","Cela dépend uniquement du langage"],
  bonne:0,
  explain:"Les microservices déplacent la complexité du code vers le réseau et l'exploitation. Loi de Conway : l'architecture reflétera l'organisation — c'est elle qui doit décider." },

{ id:"c7-24", lvl:7, dom:"SQL",
  q:"Quand choisir du NoSQL plutôt que du relationnel ?",
  choix:["Quand le modèle d'ACCÈS est connu à l'avance, par clé, avec besoin d'échelle horizontale et de latence constante","Quand le volume dépasse 1 To","Quand on veut éviter d'écrire du SQL","Quand l'application est en microservices"],
  bonne:0,
  explain:"On choisit selon le modèle d'accès, pas selon la mode. En banque le relationnel reste dominant : cohérence transactionnelle et auditabilité priment." },

{ id:"c7-25", lvl:7, dom:"SQL",
  q:"En cas de partition réseau, que choisit-on pour un solde de compte ?",
  choix:["La cohérence (CP) : mieux vaut refuser de répondre que donner un solde faux","La disponibilité (AP) : l'utilisateur doit toujours voir quelque chose","Les deux sont possibles simultanément","Cela dépend de la charge"],
  bonne:0,
  explain:"CAP : en cas de partition, il faut choisir. Pour un catalogue produit on prendrait AP. PACELC complète : hors partition, l'arbitrage devient latence vs cohérence." },

{ id:"c7-26", lvl:7, dom:"Messagerie",
  q:"Dans Kafka, qu'est-ce qui plafonne le parallélisme d'un consumer group ?",
  choix:["Le nombre de partitions du topic","Le nombre de brokers","La rétention configurée","La taille des messages"],
  bonne:0,
  explain:"Un 11ᵉ consommateur sur un topic de 10 partitions restera inactif. Et le nombre de partitions ne peut qu'augmenter, jamais diminuer." },

{ id:"c7-27", lvl:7, dom:"Messagerie",
  q:"Dans Kafka, l'ordre des messages est garanti :",
  choix:["Uniquement à l'intérieur d'une partition","Sur tout le topic","Par consumer group","Uniquement en mode transactionnel"],
  bonne:0,
  explain:"Si l'ordre compte pour un client donné, sa clé doit toujours le ranger dans la même partition. C'est tout l'enjeu du choix de la clé de partition." },

{ id:"c7-28", lvl:7, dom:"Messagerie",
  q:"Quelle garantie de livraison vise-t-on en pratique dans un système financier ?",
  choix:["At least once, avec un traitement IDEMPOTENT côté consommateur","At most once, pour éviter tout doublon","Exactly once, garanti de bout en bout par le broker","Aucune garantie, on accepte les pertes"],
  bonne:0,
  explain:"L'exactly-once de bout en bout entre systèmes hétérogènes est un mythe. Ce qu'on obtient, c'est un effet observable exactement une fois — grâce à une clé d'idempotence." },

{ id:"c7-29", lvl:7, dom:"Messagerie",
  q:"Quelle métrique surveille-t-on en priorité sur un consommateur Kafka ?",
  choix:["Le consumer lag : le retard en messages","Le nombre de brokers actifs","La taille moyenne des messages","Le nombre de topics"],
  bonne:0,
  explain:"À compléter par l'âge du plus vieux message : 10 000 messages de retard sur un flux rapide n'est pas grave, 30 minutes d'âge oui. KEDA sait autoscaler sur le lag." },

{ id:"c7-30", lvl:7, dom:"Ansible",
  q:"Terraform et Ansible : quelle répartition des rôles ?",
  choix:["Terraform provisionne l'infrastructure, Ansible configure ce qui se passe DANS la machine","Ansible provisionne, Terraform configure","Ce sont deux concurrents, il faut choisir","Ansible remplace Terraform depuis les collections cloud"],
  bonne:0,
  explain:"Dans une approche immuable, on préfère Packer + Ansible pour construire une image dorée, et Terraform pour déployer cette image — on remplace les machines au lieu de les modifier." },

{ id:"c7-31", lvl:7, dom:"Ansible",
  q:"Qu'est-ce qui casse l'idempotence d'un playbook Ansible ?",
  choix:["L'usage du module <code>shell</code>/<code>command</code> sans <code>creates</code>, <code>when</code> ou <code>changed_when</code>","L'utilisation de rôles","Les handlers","Les variables de groupe"],
  bonne:0,
  explain:"Ansible ne peut pas deviner si une commande arbitraire est nécessaire : il l'exécute toujours. L'idempotence vient des MODULES dédiés." },

{ id:"c7-32", lvl:7, dom:"Ansible",
  q:"Quel est l'équivalent Ansible du <code>terraform plan</code> ?",
  choix:["<code>ansible-playbook --check --diff</code>","<code>ansible-playbook --syntax-check</code>","<code>ansible-lint</code>","<code>ansible-inventory --graph</code>"],
  bonne:0,
  explain:"Limite honnête : en mode check, une tâche dépendant du résultat d'une tâche non exécutée peut échouer ou rapporter faux." },

{ id:"c7-33", lvl:7, dom:"GitOps",
  q:"Quel est le principal bénéfice sécurité du GitOps par rapport au push ?",
  choix:["Aucun credential de cluster n'est stocké dans la CI : c'est l'agent interne qui tire","Les manifestes sont chiffrés dans Git","Le cluster devient inaccessible depuis internet","Les images sont signées automatiquement"],
  bonne:0,
  explain:"Autres bénéfices : dérive détectée et corrigée, rollback = <code>git revert</code>, audit natif. En banque, l'approbation d'une PR devient l'autorisation de mise en production." },

{ id:"c7-34", lvl:7, dom:"GitOps",
  q:"Avec <code>selfHeal</code> activé dans Argo CD, que se passe-t-il si un ingénieur modifie un Deployment à la main pendant un incident ?",
  choix:["Argo annule sa correction en quelques secondes pour revenir à l'état déclaré dans Git","La modification est acceptée et poussée dans Git","Argo passe l'application en Degraded sans agir","Rien, selfHeal ne concerne que les suppressions"],
  bonne:0,
  explain:"D'où l'importance de savoir SUSPENDRE la synchronisation pendant un incident, puis de faire passer le correctif par Git." },

{ id:"c7-35", lvl:7, dom:"GitOps",
  q:"Comment gère-t-on les secrets en GitOps ?",
  choix:["External Secrets Operator ou CSI : le secret reste dans le coffre, le cluster le synchronise","On les commite chiffrés en base64","On les passe en variables d'environnement du pipeline","On les saisit manuellement après chaque déploiement"],
  bonne:0,
  explain:"Alternative : Sealed Secrets / SOPS (chiffré dans Git, déchiffrable par le seul cluster). En banque on préfère le coffre externe : rotation centralisée et accès audité." }

]);
