window.QCM = (window.QCM || []).concat([
/* ============ QCM NIVEAU 2 — BASES OPÉRATIONNELLES ============ */

{ id:"c2-01", lvl:2, dom:"Linux",
  q:"Quelle commande liste les ports en écoute avec le processus associé ?",
  choix:["<code>ss -tulnp</code>","<code>ps aux | grep port</code>","<code>ls /proc/net</code>","<code>ifconfig -a</code>"],
  bonne:0,
  explain:"t=TCP, u=UDP, l=listening, n=numérique (pas de résolution DNS), p=processus. <code>lsof -i :8080</code> fait le chemin inverse : du port vers le process." },

{ id:"c2-02", lvl:2, dom:"Linux",
  q:"<code>df -h</code> annonce un disque plein, mais <code>du -sh</code> ne trouve rien. Cause la plus probable ?",
  choix:["Un fichier supprimé mais toujours ouvert par un processus","Une erreur d'affichage de df","Le disque est chiffré","Un autre utilisateur cache des fichiers"],
  bonne:0,
  explain:"L'inode n'est libéré qu'à la fermeture du descripteur. <code>lsof | grep deleted</code> le révèle — typiquement un log rotaté sans signal au process. Autre piste : inodes épuisés (<code>df -i</code>)." },

{ id:"c2-03", lvl:2, dom:"Linux",
  q:"Quelle est la différence essentielle entre SIGTERM et SIGKILL ?",
  choix:["SIGTERM est interceptable (arrêt propre), SIGKILL est traité par le noyau et ne l'est pas","SIGKILL est plus lent mais plus sûr","SIGTERM ne fonctionne que sur les daemons","SIGKILL demande confirmation"],
  bonne:0,
  explain:"SIGTERM (15) laisse le process fermer ses connexions et flusher ses buffers. SIGKILL (9) est brutal. C'est exactement la logique du <code>terminationGracePeriodSeconds</code> Kubernetes." },

{ id:"c2-04", lvl:2, dom:"Linux",
  q:"À quoi sert <code>set -euo pipefail</code> en tête d'un script ?",
  choix:["Arrêter au premier échec, échouer sur variable non définie, propager l'échec dans un pipe","Activer le mode verbeux et la coloration","Optimiser la vitesse d'exécution","Rendre le script compatible POSIX"],
  bonne:0,
  explain:"<code>-u</code> évite notamment le catastrophique <code>rm -rf $DIR/</code> avec DIR vide. <code>pipefail</code> évite qu'un <code>cmd_qui_echoue | tee log</code> soit vu comme un succès." },

{ id:"c2-05", lvl:2, dom:"Linux",
  q:"Un exit code de 137 dans un conteneur signifie généralement :",
  choix:["Le processus a été tué par SIGKILL — souvent l'OOM killer","Le fichier de configuration est introuvable","Le port est déjà utilisé","L'image est corrompue"],
  bonne:0,
  explain:"128 + numéro du signal. 137 = 128+9 = SIGKILL, 143 = 128+15 = SIGTERM. Dans Kubernetes, 137 avec <code>OOMKilled</code> dans <code>describe</code> = dépassement de la limite mémoire." },

{ id:"c2-06", lvl:2, dom:"Git",
  q:"Pourquoi ne jamais faire de <code>rebase</code> sur une branche déjà partagée ?",
  choix:["Le rebase réécrit l'historique et crée de nouveaux hash : les collègues divergent","Le rebase supprime les commits des autres","Git refuse le rebase sur une branche distante","Le rebase efface les messages de commit"],
  bonne:0,
  explain:"En pratique : rebase local pour nettoyer avant la PR, merge pour intégrer. Le rebase sur une branche partagée oblige tout le monde à recoller son historique." },

{ id:"c2-07", lvl:2, dom:"Git",
  q:"Tu as commité un mot de passe puis fait <code>git revert</code>. Le secret est-il protégé ?",
  choix:["Non : le blob reste dans l'historique. Il faut RÉVOQUER le secret","Oui, le revert supprime le contenu","Oui, si on force le push ensuite","Oui, après un git gc"],
  bonne:0,
  explain:"<code>revert</code> ajoute un commit qui annule l'effet, pas le contenu. Ordre correct : révoquer le secret (seule action qui compte), puis réécrire l'historique, purger forks et caches, auditer l'usage." },

{ id:"c2-08", lvl:2, dom:"Git",
  q:"Quel <code>git reset</code> détruit le travail non commité ?",
  choix:["<code>--hard</code>","<code>--soft</code>","<code>--mixed</code>","Aucun des trois"],
  bonne:0,
  explain:"<code>--soft</code> garde index et fichiers, <code>--mixed</code> (défaut) vide l'index mais garde les fichiers, <code>--hard</code> écrase tout. Récupérable seulement via le reflog, et seulement si c'était commité." },

{ id:"c2-09", lvl:2, dom:"Docker",
  q:"Quel est le rôle respectif d'ENTRYPOINT et de CMD ?",
  choix:["ENTRYPOINT est l'exécutable fixe, CMD fournit les arguments par défaut remplaçables","CMD s'exécute au build, ENTRYPOINT au run","ENTRYPOINT est optionnel, CMD est obligatoire","Ils sont interchangeables"],
  bonne:0,
  explain:"Combo typique : <code>ENTRYPOINT [\"nginx\"]</code> + <code>CMD [\"-g\",\"daemon off;\"]</code>. Toujours en forme exec (JSON) pour que le process reçoive les signaux." },

{ id:"c2-10", lvl:2, dom:"Docker",
  q:"Pourquoi copie-t-on <code>package.json</code> et installe-t-on les dépendances AVANT de copier le code ?",
  choix:["Pour que la couche des dépendances reste en cache tant que package.json ne change pas","Parce que npm exige cet ordre","Pour réduire la taille de l'image finale","Pour éviter les conflits de permissions"],
  bonne:0,
  explain:"Toute modification d'un fichier invalide sa couche ET toutes les suivantes. Copier le code en premier relancerait un <code>npm install</code> complet à chaque changement de source." },

{ id:"c2-11", lvl:2, dom:"Docker",
  q:"Qu'apporte un build multi-stage ?",
  choix:["On compile dans une image lourde et on ne livre que l'artefact dans une image minimale","On peut construire plusieurs images en parallèle","On accélère le téléchargement des couches","On permet le build multi-architecture"],
  bonne:0,
  explain:"Résultat : image beaucoup plus petite, sans compilateur ni sources — donc surface d'attaque, temps de pull et coût de stockage réduits." },

{ id:"c2-12", lvl:2, dom:"Docker",
  q:"Que fait réellement <code>EXPOSE 8080</code> dans un Dockerfile ?",
  choix:["Rien de fonctionnel : c'est une métadonnée documentaire","Il ouvre le port sur l'hôte","Il configure le firewall du conteneur","Il réserve le port pour éviter les conflits"],
  bonne:0,
  explain:"Pour joindre le port depuis l'hôte il faut <code>-p 8080:8080</code> au run, ou un Service côté Kubernetes. Beaucoup de candidats se trompent là-dessus." },

{ id:"c2-13", lvl:2, dom:"Kubernetes",
  q:"Quelle est la chaîne d'objets entre un Deployment et un Pod ?",
  choix:["Deployment → ReplicaSet → Pod","Deployment → Pod directement","Deployment → Service → Pod","Deployment → DaemonSet → Pod"],
  bonne:0,
  explain:"Le Deployment crée un NOUVEAU ReplicaSet à chaque changement de template et fait varier les réplicas des deux. Les anciens RS sont conservés pour permettre le rollback." },

{ id:"c2-14", lvl:2, dom:"Kubernetes",
  q:"Que se passe-t-il quand une readiness probe échoue ?",
  choix:["Le Pod est retiré des Endpoints du Service : plus de trafic, mais il reste vivant","Le conteneur est redémarré","Le Pod est supprimé et recréé","Le nœud est marqué NotReady"],
  bonne:0,
  explain:"C'est la liveness qui redémarre. Readiness = « prêt à recevoir du trafic ». Confondre les deux est l'erreur la plus fréquente sur Kubernetes." },

{ id:"c2-15", lvl:2, dom:"Kubernetes",
  q:"Un Secret Kubernetes est-il chiffré par défaut ?",
  choix:["Non : il est seulement encodé en base64 dans etcd","Oui, avec AES-256","Oui, si le cluster est managé","Oui, mais uniquement en transit"],
  bonne:0,
  explain:"Il faut activer l'<code>EncryptionConfiguration</code> côté API server, ou externaliser (External Secrets Operator, CSI Secret Store). Et surtout restreindre le RBAC sur les Secrets." },

{ id:"c2-16", lvl:2, dom:"Kubernetes",
  q:"Quelle est la différence entre un label et une annotation ?",
  choix:["Les labels sont indexés et servent à SÉLECTIONNER des objets ; les annotations portent des métadonnées non sélectionnables","Les annotations sont visibles, les labels sont internes","Les labels sont limités à 3 par objet","Aucune différence technique"],
  bonne:0,
  explain:"Services, ReplicaSets et NetworkPolicies fonctionnent par <code>selector</code> sur les labels. Les annotations transportent de la config d'outil, des checksums, des données volumineuses." },

{ id:"c2-17", lvl:2, dom:"Kubernetes",
  q:"Que fait <code>kubectl apply</code> qu'un <code>kubectl create</code> ne fait pas ?",
  choix:["Il est idempotent : il crée OU met à jour l'objet","Il valide le YAML avant envoi","Il crée les namespaces manquants","Il attend que les Pods soient prêts"],
  bonne:0,
  explain:"<code>create</code> échoue si l'objet existe déjà. <code>apply</code> calcule un diff et converge. En pipeline, c'est toujours <code>apply</code>." },

{ id:"c2-18", lvl:2, dom:"Terraform",
  q:"Que signifie <code>-/+</code> dans un plan Terraform ?",
  choix:["La ressource sera DÉTRUITE puis RECRÉÉE","Elle sera modifiée en place","Elle sera renommée","Elle sera ignorée"],
  bonne:0,
  explain:"<code>+</code> création, <code>-</code> destruction, <code>~</code> modification en place, <code>-/+</code> remplacement. Toujours chercher la mention <code># forces replacement</code> pour savoir quel attribut immuable a changé." },

{ id:"c2-19", lvl:2, dom:"Terraform",
  q:"Pourquoi un backend distant est-il indispensable en équipe ?",
  choix:["Pour partager le state ET le verrouiller pendant un apply","Pour accélérer le téléchargement des providers","Pour chiffrer le code source","Pour permettre le travail hors ligne"],
  bonne:0,
  explain:"Sans verrou, deux <code>apply</code> simultanés corrompent le state ou créent des doublons. S3+DynamoDB, azurerm avec bail de blob, ou HCP Terraform." },

{ id:"c2-20", lvl:2, dom:"Terraform",
  q:"Le fichier <code>.terraform.lock.hcl</code> doit-il être commité ?",
  choix:["Oui : il fige les versions et empreintes des providers pour tout le monde","Non, il est propre à chaque machine","Non, il contient des secrets","Seulement en production"],
  bonne:0,
  explain:"C'est ce qui garantit que ton poste, celui du collègue et la CI utilisent strictement les mêmes providers. À ne pas confondre avec le verrou de state." },

{ id:"c2-21", lvl:2, dom:"Terraform",
  q:"Quelle contrainte de version protège d'une montée de version majeure ?",
  choix:["<code>~&gt; 4.0</code>","<code>&gt;= 4.0</code>","<code>!= 3.0</code>","<code>latest</code>"],
  bonne:0,
  explain:"L'opérateur pessimiste <code>~&gt;</code> autorise 4.1 et 4.9 mais pas 5.0. <code>&gt;= 4.0</code> accepterait une v5 qui casse tout du jour au lendemain." },

{ id:"c2-22", lvl:2, dom:"AWS",
  q:"Qu'est-ce qui rend un subnet AWS « public » ?",
  choix:["Une route <code>0.0.0.0/0</code> vers l'Internet Gateway dans sa route table","Son nom contenant « public »","La présence d'une NAT Gateway","Un Security Group ouvert"],
  bonne:0,
  explain:"Le nom n'a aucune valeur technique. Il faut aussi une IP publique (ou EIP) sur l'instance pour qu'elle soit joignable de l'extérieur." },

{ id:"c2-23", lvl:2, dom:"AWS",
  q:"Un Security Group est stateful. Qu'est-ce que ça change ?",
  choix:["Le trafic de retour est automatiquement autorisé, sans règle sortante","Il mémorise les IP bloquées","Il s'applique à tout le subnet","Il journalise chaque connexion"],
  bonne:0,
  explain:"Une NACL, elle, est stateless : il faut une règle explicite dans CHAQUE sens, y compris sur les ports éphémères (1024-65535) pour le retour." },

{ id:"c2-24", lvl:2, dom:"AWS",
  q:"Pourquoi préférer un IAM Role à un IAM User pour une application sur EC2 ?",
  choix:["Le rôle délivre des credentials temporaires à rotation automatique — aucune clé statique","Le rôle est moins cher","Le rôle permet plus de permissions","Le rôle fonctionne sans réseau"],
  bonne:0,
  explain:"Instance profile sur EC2, IRSA sur EKS, OIDC pour la CI. Les clés d'accès statiques codées en dur sont la première cause de fuite en entreprise." },

{ id:"c2-25", lvl:2, dom:"Azure",
  q:"Quel est l'avantage principal d'une Managed Identity sur un Service Principal ?",
  choix:["Aucun secret à stocker ni à faire tourner : Azure gère le cycle de vie","Elle coûte moins cher","Elle donne plus de permissions","Elle fonctionne hors d'Azure"],
  bonne:0,
  explain:"Le token est récupéré via l'endpoint IMDS. Un Service Principal impose de gérer un secret ou un certificat, avec son expiration et sa rotation." },

{ id:"c2-26", lvl:2, dom:"Azure",
  q:"Dans quel cas une Managed Identity user-assigned est-elle nécessaire ?",
  choix:["Quand on veut assigner les droits RBAC AVANT de créer la ressource, ou la partager entre plusieurs ressources","Quand la ressource est dans un autre tenant","Quand on a besoin d'un mot de passe","Quand la ressource est éphémère"],
  bonne:0,
  explain:"System-assigned est liée au cycle de vie de sa ressource (1:1, supprimée avec elle). User-assigned est un objet indépendant — ce qui règle le problème poule/œuf en Terraform." },

{ id:"c2-27", lvl:2, dom:"Azure",
  q:"Comment sont évaluées les règles d'un NSG ?",
  choix:["Par priorité croissante, la première qui correspond s'applique et l'évaluation s'arrête","Toutes les règles sont évaluées, le Deny gagne toujours","Par ordre alphabétique du nom","De la plus récente à la plus ancienne"],
  bonne:0,
  explain:"Piège classique : une règle Allow en priorité 300 qui ne sert jamais parce qu'un Deny existe en 200. Des règles par défaut existent en fin de liste." },

{ id:"c2-28", lvl:2, dom:"Réseau",
  q:"Quelles sont les trois étapes du handshake TCP ?",
  choix:["SYN, SYN-ACK, ACK","HELLO, ACK, DATA","OPEN, CONFIRM, CLOSE","REQUEST, RESPONSE, ACK"],
  bonne:0,
  explain:"Une connexion bloquée en SYN_SENT côté client, c'est presque toujours un firewall qui DROP silencieusement — un REJECT donnerait un « connection refused » immédiat." },

{ id:"c2-29", lvl:2, dom:"Réseau",
  q:"Dans un handshake TLS, à quoi sert la partie asymétrique ?",
  choix:["À authentifier le serveur et établir une clé de session symétrique","À chiffrer tout le trafic de la session","À compresser les données","À vérifier l'intégrité des paquets"],
  bonne:0,
  explain:"L'asymétrique est lent : il ne sert qu'à établir la confiance et négocier la clé (ECDHE, d'où la forward secrecy). Le trafic est ensuite chiffré en symétrique (AES)." },

{ id:"c2-30", lvl:2, dom:"Réseau",
  q:"Quand choisit-on un load balancer L7 plutôt que L4 ?",
  choix:["Quand on a besoin de router par URL, host ou header, ou de terminer le TLS","Quand on veut la latence la plus faible possible","Quand le protocole n'est pas HTTP","Quand on a besoin d'une IP statique"],
  bonne:0,
  explain:"L4 (NLB, Azure LB) route sur IP/port sans lire le contenu : rapide, tout protocole, IP source préservée. L7 (ALB, App Gateway, Ingress) comprend HTTP." },

{ id:"c2-31", lvl:2, dom:"CI/CD",
  q:"Dans quel ordre ranger les étapes d'un pipeline pour un feedback rapide ?",
  choix:["Lint → tests unitaires → build → scan sécurité → tests d'intégration → déploiement","Build → déploiement → tests → lint","Tests d'intégration → tests unitaires → build","Scan sécurité → déploiement → build → tests"],
  bonne:0,
  explain:"Le moins coûteux et le plus discriminant d'abord (<em>fail fast</em>). Objectif : un retour utile en moins de 10 minutes sur une PR." },

{ id:"c2-32", lvl:2, dom:"CI/CD",
  q:"Pourquoi ne jamais taguer une image de production en <code>latest</code> ?",
  choix:["C'est un tag mutable : on ne sait plus ce qui tourne et le rollback devient impossible","Docker Hub facture les tags latest","Le tag latest est réservé aux images officielles","Il ralentit le pull"],
  bonne:0,
  explain:"En production, on référence idéalement le digest immuable (<code>@sha256:…</code>). Un tag peut être réaffecté à tout moment : il ne prouve rien." },

{ id:"c2-33", lvl:2, dom:"Sécurité",
  q:"Pourquoi ne pas passer un secret via <code>ARG</code> dans un Dockerfile ?",
  choix:["Il reste visible dans l'historique des couches (<code>docker history</code>)","Les ARG sont limités à 64 caractères","Docker les convertit en clair dans les logs de build uniquement","Ils ne sont pas transmis au conteneur"],
  bonne:0,
  explain:"Quiconque a l'image a le secret. Solutions : BuildKit <code>--mount=type=secret</code>, ou injection au RUNTIME depuis un coffre." },

{ id:"c2-34", lvl:2, dom:"Observabilité",
  q:"Pourquoi préférer des logs structurés en JSON ?",
  choix:["Ils sont indexables et requêtables par champ, sans regex fragile","Ils prennent moins de place","Ils sont chiffrés par défaut","Ils sont plus lisibles pour un humain"],
  bonne:0,
  explain:"Champs indispensables : timestamp, level, service, version, environnement, trace_id. Le texte libre casse dès qu'un dev change le format d'un message." },

{ id:"c2-35", lvl:2, dom:"SRE",
  q:"Qu'est-ce qu'un post-mortem « blameless » ?",
  choix:["Une analyse qui cherche les causes systémiques plutôt qu'un coupable","Un rapport rédigé sans nommer l'incident","Une réunion sans compte rendu écrit","Un post-mortem rédigé par un tiers externe"],
  bonne:0,
  explain:"Objectif : que les gens rapportent les incidents sans peur. Chercher un coupable fait taire l'information et garantit la récidive." }

]);
